<h3>Yaws 1.83</h3>
<h4><small>juillet 03, 2009</small></h4>
<p>Yaws 1.83 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 22 commits</small></ol>
  <ol>Olivier Girondel <small class="text-muted"> 16 commits</small></ol>
  <ol>Fabian Alenius <small class="text-muted"> 15 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 4 commits</small></ol>
  <ol>dnz@bk.ru <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.83">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
