<h3>Yaws 1.85</h3>
<h4><small>octobre 17, 2009</small></h4>
<p>Yaws 1.85 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 33 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 29 commits</small></ol>
  <ol>davide <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.85">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
