<h3>Yaws 1.82</h3>
<h4><small>mai 28, 2009</small></h4>
<p>Yaws 1.82 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 20 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 19 commits</small></ol>
  <ol>Fabian Alenius <small class="text-muted"> 5 commits</small></ol>
  <ol>Hans Ulrich Niedermann <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.82">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
