<h3>Yaws 1.84</h3>
<h4><small>juillet 05, 2009</small></h4>
<p>Yaws 1.84 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 4 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.84">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
