<h3>Yaws 1.81</h3>
<h4><small>mars 10, 2009</small></h4>
<p>Yaws 1.81 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 784 commits</small></ol>
  <ol>Johan Bevemyr <small class="text-muted"> 206 commits</small></ol>
  <ol>Carsten Schultz <small class="text-muted"> 79 commits</small></ol>
  <ol>Tobbe Tornquist <small class="text-muted"> 73 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 46 commits</small></ol>
  <ol>Mikael Karlsson <small class="text-muted"> 22 commits</small></ol>
  <ol>Mickael Remond <small class="text-muted"> 17 commits</small></ol>
  <ol>Leon Smith <small class="text-muted"> 12 commits</small></ol>
  <ol>Luke Gorrie <small class="text-muted"> 12 commits</small></ol>
  <ol>Martin Bjorklund <small class="text-muted"> 9 commits</small></ol>
  <ol>Yariv Sadan <small class="text-muted"> 8 commits</small></ol>
  <ol>Hans Ulrich Niedermann <small class="text-muted"> 7 commits</small></ol>
  <ol>Julian Noble <small class="text-muted"> 6 commits</small></ol>
  <ol>Seah Hinde <small class="text-muted"> 4 commits</small></ol>
  <ol>Bruce Fitzsimmons <small class="text-muted"> 2 commits</small></ol>
  <ol>Sebastian Stroll <small class="text-muted"> 2 commits</small></ol>
  <ol>Anders Nygren <small class="text-muted"> 1 commits</small></ol>
  <ol>Jocke Grebeno <small class="text-muted"> 1 commits</small></ol>
  <ol>None one <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.81">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
