<h3>Yaws 1.86</h3>
<h4><small>décembre 06, 2009</small></h4>
<p>Yaws 1.86 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 17 commits</small></ol>
  <ol>Paul Hampson <small class="text-muted"> 7 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 6 commits</small></ol>
  <ol>Eric Liang <small class="text-muted"> 4 commits</small></ol>
  <ol>Torbjorn Tornkvist <small class="text-muted"> 2 commits</small></ol>
  <ol>davide <small class="text-muted"> 2 commits</small></ol>
  <ol>Matt Stancliff <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.86">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
