<h3>Yaws 1.88</h3>
<h4><small>mars 18, 2010</small></h4>
<p>Yaws 1.88 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 17 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 4 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.88">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
