<h3>Yaws 1.87</h3>
<h4><small>février 09, 2010</small></h4>
<p>Yaws 1.87 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 15 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 7 commits</small></ol>
  <ol>davide <small class="text-muted"> 4 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.87">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
