<h3>Yaws 1.89</h3>
<h4><small>septembre 25, 2010</small></h4>
<p>Yaws 1.89 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 37 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 11 commits</small></ol>
  <ol>Mikael Karlsson <small class="text-muted"> 4 commits</small></ol>
  <ol>Dominique Boucher <small class="text-muted"> 3 commits</small></ol>
  <ol>Thomas O'Dowd <small class="text-muted"> 2 commits</small></ol>
  <ol>Alexander Simonov <small class="text-muted"> 1 commits</small></ol>
  <ol>Anders Nygren <small class="text-muted"> 1 commits</small></ol>
  <ol>Hans-Christian Esperer <small class="text-muted"> 1 commits</small></ol>
  <ol>Joseph Wayne Norton <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.89">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
