<h3>Yaws 1.90</h3>
<h4><small>mai 25, 2011</small></h4>
<p>Yaws 1.90 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 52 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 29 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 20 commits</small></ol>
  <ol>Tuncer Ayaz <small class="text-muted"> 8 commits</small></ol>
  <ol>Torbjorn Tornkvist <small class="text-muted"> 7 commits</small></ol>
  <ol>Nicolas Thauvin <small class="text-muted"> 3 commits</small></ol>
  <ol>Per Andersson <small class="text-muted"> 3 commits</small></ol>
  <ol>Fabian Linzberger <small class="text-muted"> 2 commits</small></ol>
  <ol>Jean-Sébastien Pédron <small class="text-muted"> 2 commits</small></ol>
  <ol>Peter Lemenkov <small class="text-muted"> 2 commits</small></ol>
  <ol>Dan Willemsen <small class="text-muted"> 1 commits</small></ol>
  <ol>François de Metz <small class="text-muted"> 1 commits</small></ol>
  <ol>James Lee <small class="text-muted"> 1 commits</small></ol>
  <ol>Yurii Rashkovskii <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.90">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
