<h3>Yaws 1.92</h3>
<h4><small>décembre 23, 2011</small></h4>
<p>Yaws 1.92 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 30 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 7 commits</small></ol>
  <ol>Tuncer Ayaz <small class="text-muted"> 5 commits</small></ol>
  <ol>Essien Ita Essien <small class="text-muted"> 1 commits</small></ol>
  <ol>JD Bothma <small class="text-muted"> 1 commits</small></ol>
  <ol>Uwe Dauernheim <small class="text-muted"> 1 commits</small></ol>
  <ol>Willem de Jong <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.92">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
