<h3>Yaws 1.91</h3>
<h4><small>août 02, 2011</small></h4>
<p>Yaws 1.91 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Christopher Faulet <small class="text-muted"> 11 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 11 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 3 commits</small></ol>
  <ol>Tuncer Ayaz <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.91">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
