<h3>Yaws 1.93</h3>
<h4><small>juin 21, 2012</small></h4>
<p>Yaws 1.93 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 51 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 49 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 21 commits</small></ol>
  <ol>Tuncer Ayaz <small class="text-muted"> 8 commits</small></ol>
  <ol>Sergei Golovan <small class="text-muted"> 5 commits</small></ol>
  <ol>Garret Smith <small class="text-muted"> 4 commits</small></ol>
  <ol>Nicolas Adiba <small class="text-muted"> 2 commits</small></ol>
  <ol>Richard Carlsson <small class="text-muted"> 2 commits</small></ol>
  <ol>Andrei Soroker <small class="text-muted"> 1 commits</small></ol>
  <ol>Kaloyan Dimitrov <small class="text-muted"> 1 commits</small></ol>
  <ol>Mikael Karlsson <small class="text-muted"> 1 commits</small></ol>
  <ol>Ulf Wiger <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.93">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
