<h3>Yaws 1.95</h3>
<h4><small>octobre 17, 2012</small></h4>
<p>Yaws 1.95 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 31 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 16 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 10 commits</small></ol>
  <ol>Kaloyan Dimitrov <small class="text-muted"> 4 commits</small></ol>
  <ol>Tuncer Ayaz <small class="text-muted"> 3 commits</small></ol>
  <ol>serge <small class="text-muted"> 3 commits</small></ol>
  <ol>tjeerd <small class="text-muted"> 2 commits</small></ol>
  <ol>JD Bothma <small class="text-muted"> 1 commits</small></ol>
  <ol>Kenji Rikitake <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.95">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
