<h3>Yaws 1.98</h3>
<h4><small>novembre 04, 2013</small></h4>
<p>Yaws 1.98 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 2 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 1 commits</small></ol>
  <ol>Joseph Wayne Norton <small class="text-muted"> 1 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.98">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
