<h3>Yaws 1.97</h3>
<h4><small>octobre 16, 2013</small></h4>
<p>Yaws 1.97 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Claes Wikstrom <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.97">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
