<h3>Yaws 1.96</h3>
<h4><small>octobre 11, 2013</small></h4>
<p>Yaws 1.96 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Christopher Faulet <small class="text-muted"> 37 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 34 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 16 commits</small></ol>
  <ol>Tuncer Ayaz <small class="text-muted"> 3 commits</small></ol>
  <ol>Johannes Weißl <small class="text-muted"> 2 commits</small></ol>
  <ol>Manuel Durán Aguete <small class="text-muted"> 2 commits</small></ol>
  <ol>Ahti Legonkov <small class="text-muted"> 1 commits</small></ol>
  <ol>Corey Haines <small class="text-muted"> 1 commits</small></ol>
  <ol>Francis Joanis <small class="text-muted"> 1 commits</small></ol>
  <ol>James Lee <small class="text-muted"> 1 commits</small></ol>
  <ol>Karolis Petrauskas <small class="text-muted"> 1 commits</small></ol>
  <ol>Ning Zhang <small class="text-muted"> 1 commits</small></ol>
  <ol>Rick Reed <small class="text-muted"> 1 commits</small></ol>
  <ol>Susan Potter <small class="text-muted"> 1 commits</small></ol>
  <ol>olgeni <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.96">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
