<h3>Yaws 1.99</h3>
<h4><small>novembre 23, 2014</small></h4>
<p>Yaws 1.99 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 47 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 26 commits</small></ol>
  <ol>Johannes Weißl <small class="text-muted"> 7 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 6 commits</small></ol>
  <ol>Jean-Sébastien Pédron <small class="text-muted"> 4 commits</small></ol>
  <ol>Lastres <small class="text-muted"> 1 commits</small></ol>
  <ol>Richard Carlsson <small class="text-muted"> 1 commits</small></ol>
  <ol>Sebastian Godelet <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=1.99">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
