<h3>Yaws 2.0.2</h3>
<h4><small>octobre 07, 2015</small></h4>
<p>Yaws 2.0.2 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 10 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 9 commits</small></ol>
  <ol>Klacke <small class="text-muted"> 6 commits</small></ol>
  <ol>Andrei Neculau <small class="text-muted"> 5 commits</small></ol>
  <ol>Attila Gulyas <small class="text-muted"> 3 commits</small></ol>
  <ol>Kristoffer Koch <small class="text-muted"> 2 commits</small></ol>
  <ol>PHO <small class="text-muted"> 2 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 1 commits</small></ol>
  <ol>Ev Bogdanov <small class="text-muted"> 1 commits</small></ol>
  <ol>Johannes Weißl <small class="text-muted"> 1 commits</small></ol>
  <ol>Leo Liu <small class="text-muted"> 1 commits</small></ol>
  <ol>Yury Gargay <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=2.0.2">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
