<h3>Yaws 2.0</h3>
<h4><small>juillet 13, 2015</small></h4>
<p>Yaws 2.0 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Christopher Faulet <small class="text-muted"> 18 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 12 commits</small></ol>
  <ol>Klacke <small class="text-muted"> 6 commits</small></ol>
  <ol>Andrei Neculau <small class="text-muted"> 5 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 2 commits</small></ol>
  <ol>Mike <small class="text-muted"> 2 commits</small></ol>
  <ol>Craig Everett <small class="text-muted"> 1 commits</small></ol>
  <ol>Milton Inostroza <small class="text-muted"> 1 commits</small></ol>
  <ol>PHO <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=2.0">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
