<h3>Yaws 2.0.3</h3>
<h4><small>juin 30, 2016</small></h4>
<p>Yaws 2.0.3 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Steve Vinoski <small class="text-muted"> 19 commits</small></ol>
  <ol>Christopher Faulet <small class="text-muted"> 14 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 4 commits</small></ol>
  <ol>Leo Liu <small class="text-muted"> 4 commits</small></ol>
  <ol>Matthias Lang <small class="text-muted"> 3 commits</small></ol>
  <ol>Andrei Neculau <small class="text-muted"> 2 commits</small></ol>
  <ol>Klacke Wikstrom <small class="text-muted"> 2 commits</small></ol>
  <ol>Jesse Gumm <small class="text-muted"> 1 commits</small></ol>
  <ol>Karol Ostrovsky <small class="text-muted"> 1 commits</small></ol>
  <ol>Klacke <small class="text-muted"> 1 commits</small></ol>
  <ol>Mattias Jansson <small class="text-muted"> 1 commits</small></ol>
  <ol>Richard Carlsson <small class="text-muted"> 1 commits</small></ol>
  <ol>Stuart Thackray <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=2.0.3">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
