<h3>Yaws 2.0.4</h3>
<h4><small>septembre 22, 2016</small></h4>
<p>Yaws 2.0.4 has been released! Many thanks to following contributors for their work:</p>
<ul>
  <ol>Christopher Faulet <small class="text-muted"> 23 commits</small></ol>
  <ol>Steve Vinoski <small class="text-muted"> 3 commits</small></ol>
  <ol>Klacke Wikstrom <small class="text-muted"> 2 commits</small></ol>
  <ol>Nico <small class="text-muted"> 2 commits</small></ol>
  <ol>Christopher Meiklejohn <small class="text-muted"> 1 commits</small></ol>
  <ol>Claes Wikstrom <small class="text-muted"> 1 commits</small></ol>
  <ol>Olivier Favre <small class="text-muted"> 1 commits</small></ol>
  <ol>Torbjorn Tornkvist <small class="text-muted"> 1 commits</small></ol>
</ul>
<p>
  You can find more information or download it from
  <a href="%%webroot%%/downloads.yaws?vsn=2.0.4">the downloads page</a>
</p>
<p class="text-right text-muted">-- Yaws team</p>
<hr/>
