
include ../include.mk

install:
	install -d $(INSTALLPREFIX)/man/man1
	install -d $(INSTALLPREFIX)/man/man5
	cp yaws.1 $(INSTALLPREFIX)/man/man1
	cp yaws.conf.5 $(INSTALLPREFIX)/man/man5
	cp yaws_api.5 $(INSTALLPREFIX)/man/man5

all debug clean:
