
include ../include.mk

install:
	install -d $(DESTDIR)$(PREFIX)/share/man/man1
	install -d $(DESTDIR)$(PREFIX)/share/man/man5
	cp yaws.1 $(DESTDIR)$(PREFIX)/share/man/man1
	cp yaws.conf.5 $(DESTDIR)$(PREFIX)/share/man/man5
	cp yaws_api.5 $(DESTDIR)$(PREFIX)/share/man/man5

all debug clean:
