#!/bin/sh

#
#
input=$1
output=$2

cadaver http://localhost:8000 < $input > $output

success=`grep -c succeeded. $output`
if [ $success -ne 9 ]; then
    echo "- not all cadaver actions succeeded, see $output for details"
    exit 1
fi
printf "\n** All "`pwd`" tests completed successfully.\n\n"
exit 0

