    <header id="main-page">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h1><img src="%%webroot%%/images/yaws_head.png" class="img-responsive pull-right"></h1>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-9 col-xs-push-1">
            <h1>
              <a class="btn btn-lg btn-transparent" href="https://github.com/klacke/yaws" target="_blank">
                <img src="%%webroot%%/images/github_dark.png" alt="Github">
                Source code
              </a>
              <a class="btn btn-lg btn-transparent" href="%%webroot%%/downloads.yaws?vsn=%%version%%">
                Latest release (%%version%%)
              </a>
            </h1>
          </div>
        </div>
      </div>
    </header>
