<h2>
   <a href="https://github.com/klacke/yaws/releases/tag/%%tag%%" target="_blank">
     Yaws %%vsn%%
   </a>
   <small>(%%date%%)</small>
</h2>
<hr/>
<div>
  <h4>
    <ul class="%%tar_show_cls%%">
      <ol><a href="%%tar_link%%">Source code</a> <small>(size: %%tar_size%% bytes)</small></ol>
      <ol><small class="sha256">[SHA256: %%tar_sha256%%]</small></ol>
    </ul>
    <ul class="%%tar_hide_cls%%">
      <ol><small class="alert-danger">Source code (not available)</small></ol>
    </ul>
  </h4>
  <h4>
    <ul class="%%exe_show_cls%%">
      <ol><a href="%%exe_link%%">Windows 32-bit Binary File</a> <small>(size: %%exe_size%% bytes)</small></ol>
      <ol><small class="sha256">[SHA256: %%exe_sha256%%]</small></ol>
    </ul>
    <ul class="%%exe_hide_cls%%">
      <ol><small class="alert-danger">Windows 32-bit Binary File (not available)</small></ol>
    </ul>
  </h4>
</div>
