    <!-- Modal -->
    <div class="modal fade" id="yawsModal" role="dialog" aria-labelledby="yawsModalLabel">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close"
                    data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <h2 class="modal-title text-center" id="yawsModalLabel"></h2>
          </div>
          <div class="modal-body"></div>
        </div>
      </div>
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-2">
            <img src="%%webroot%%/images/yaws_pb.gif" class="img-responsive">
          </div>
        </div>
      </div>
    </footer>

    <!-- script references -->
    <script src="%%webroot%%/js/jquery.min.js"></script>
    <script src="%%webroot%%/js/jquery-scrolltofixed.min.js"></script>
    <script src="%%webroot%%/js/bootstrap.min.js"></script>
    <script src="%%webroot%%/js/highlight.pack.js"></script>
    <script src="%%webroot%%/js/scripts.js"></script>
  </body>
</html>
