<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Yaws - Yet Another Web Server</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="%%webroot%%/css/bootstrap.min.css" rel="stylesheet">
    <link href="%%webroot%%/css/highlight/zenburn.css" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    <link href="%%webroot%%/css/styles.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="%%webroot%%/images/yaws_ico.png" />
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top" role="banner">
      <div class="container">
        <ul class="nav navbar-nav">
          <li>
            <a href="%%webroot%%/index.yaws" class="navbar-brand">
              <img src="%%webroot%%/images/yaws_logo.png" class="img-responsive">
            </a>
          </li>
          <li>
            <a href="%%webroot%%/get_started.yaws">Get Started</a>
          </li>
          <li>
            <a href="%%webroot%%/documentation.yaws">Documentation</a>
          </li>
          <li>
            <a href="%%webroot%%/howtos.yaws">How to</a>
          </li>
          <li>
            <a href="%%webroot%%/downloads.yaws">Downloads</a>
          </li>
          <li>
            <a href="https://github.com/klacke/yaws">
              <img src="%%webroot%%/images/github_light.png" data-hover="%%webroot%%/images/github.png" alt="Github">
            </a>
          </li>
        </ul>
      </div>
    </nav>
