-module(my_soap).
-export([handler/4]).
-include("my_soap.hrl").  % .hrl file generated by erlsom

handler(_Header, [#'p:GetWeatherByPlaceName'{'PlaceName' = Place}],
        _Action, _SessionValue) ->
    {ok, undefined, get_weather_info(Place)}.

get_weather_info(Place) ->
    WeatherData =
        #'p:WeatherData'{anyAttribs        = [],
                         'Day'             = "Sunday, December 10, 2006",
                         'WeatherImage'    = "http://www.nws.noaa.gov/weather/images/fcicons/nfew.jpg",
                         'MaxTemperatureF' = "51",
                         'MinTemperatureF' = "28",
                         'MaxTemperatureC' = "11",
                         'MinTemperatureC' = "-2"},
    ArrayOfWeatherData =
        #'p:ArrayOfWeatherData'{anyAttribs    = [],
                                'WeatherData' = [WeatherData]},
    Forecast =
        #'p:WeatherForecasts'{anyAttribs         = [],
                              'Latitude'         = "40.3044128",
                              'Longitude'        = "79.81284",
                              'AllocationFactor' = "0.000453",
                              'FipsCode'         = "42",
                              'PlaceName'        = Place,
                              'StateCode'        = "PA",
                              'Status'           = undefined,
                              'Details'          = ArrayOfWeatherData},
    Response =
        #'p:GetWeatherByPlaceNameResponse'{anyAttribs                    = [],
                                           'GetWeatherByPlaceNameResult' = Forecast},
    [Response].
