
<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head>
 <meta name="keywords" content="Yaws"/>
 <title>Yapp</title>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
 <link rel="stylesheet" type="text/css" href="stil.css"/>
 <link rel="shortcut icon" href="/icons/yaws_y.gif" type="image/x-icon"/>
</head>

<body>

<div class="logo">
   <img src="/icons/yaws_head.gif" width="600" alt="YAWS"/>
</div>


<div id="sidebar">
<h4> Yapp </h4>
<div class="%%list%%"> <a href="index.yaws" id="list">List</a></div>
<div class="%%add%%"> <a href="add.yaws" id="Add" >Add</a> </div>
<div class="%%remove%%"> <a href="remove.yaws" id="remove">Remove</a> </div>
</div>

<div id="entry">
<h2>Yapp admin console</h2>





