
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN"
			"http://www.w3.org/TR/REC-html40/loose.dtd">
<html>

<head>
 <meta name="keywords" content="Yaws">
 <title>Yaws</title>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <link rel="stylesheet" type="text/css" href="stil.css">
 <link REL="shortcut icon" href="/icons/yaws_y.gif" TYPE="image/x-icon">
</head>

<body>




<img src="icons/yaws_head.gif" width="600" alt="YAWS">


<div id="sidebar">
<h4> Yaws </h4>
<a href="index.yaws" id="index" >Top Page</a> 
<a href="configuration.yaws" id="configuration">Build Config & Run</a>
<a href="dynamic.yaws" id="dynamic" >Dynamic content</a>
<a href="contribs.yaws" id="contribs">Contribs/Apps</a> 
<a href="download" id="download">Download </a> 
<a href="contact.yaws" id="contact">Contact </a> 
<a href="doc.yaws" id="doc">Documentation</a> 
<h4> Examples </h4>
<a href="/simple.yaws">Simple</a>
<a href="/dynamic.yaws">Dynamic content</a>
<a href="/query.yaws">Query part of url</a>
<a href="/form.yaws">Forms</a>
<a href="/redirect.yaws">Redirect</a>
<a href="/arg.yaws">Arg</a>
<a href="/ssi.yaws">Server side includes</a>
<a href="/bindings.yaws">Bindings</a>
<a href="/upload0.yaws">File upload</a>
<a href="/cookies.yaws">Cookies</a> 
<a href="/pcookie.yaws">Persistent Cookies</a> 
<a href="/session.yaws">Cookie sessions</a>   
<a href="/appmods.yaws">Appmods</a> 
<a href="/stream.yaws">Streaming data</a>
<a href="/shopingcart/index.yaws">Tiny shopping cart</a>
<a href="/embed.yaws">Embedding Yaws</a>





</div>




