
<!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head>
 <meta name="keywords" content="Yaws"/>
 <title>Yaws</title>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
 <link rel="stylesheet" type="text/css" href="stil.css"/>
 <link rel="shortcut icon" href="/icons/yaws_y.gif" type="image/x-icon"/>
</head>

<body>



<div class="logo">
   <img src="icons/yaws_head.gif" width="600" alt="YAWS"/>
</div>



<div id="sidebar">
<h4> Yaws </h4>
<div class="%%index%%"> <a href="index.yaws" id="index" >Top Page</a> </div>
<div class="%%configuration%%"> <a href="configuration.yaws" id="configuration">Build Config and Run</a></div>
<div class="%%dynamic%%"> <a href="dynamic.yaws" id="dynamic" >Dynamic content</a> </div>
<div class="%%contribs%%"> <a href="contribs.yaws" id="contribs">Contribs/Apps</a> </div>
<div class="%%download%%"> <a href="http://yaws.hyber.org/download/" id="download">Download </a> </div>
<div class="%%contact%%"> <a href="contact.yaws" id="contact">Contact </a> </div>
<div class="%%doc%%"> <a href="doc.yaws" id="doc">Documentation</a>  </div>
<div class="%%wiki%%"> <a href="http://wiki.github.com/klacke/yaws" id="wiki">Wiki</a>  </div>

<h4> Examples </h4>
<div class="%%json_intro%%"> <a href="/json_intro.yaws">AJAX/Json RPC</a></div>
<div class="%%appmods%%"> <a href="/appmods.yaws">Appmods</a> </div>
<div class="%%arg%%"> <a href="/arg.yaws">Arg</a> </div>
<div class="%%privbind%%"> <a href="/privbind.yaws">Binding to privileged ports</a></div>
<div class="%%bindings%%"> <a href="/bindings.yaws">Bindings</a> </div>
<div class="%%cgi%%"> <a href="/cgi.yaws">CGI</a></div>
<div class="%%session%%"> <a href="/session.yaws">Cookie sessions</a>   </div>
<div class="%%cookies%%"> <a href="/cookies.yaws">Cookies</a>  </div>
<div class="%%dynamic%%"> <a href="/dynamic.yaws">Dynamic content</a> </div>
<div class="%%embed%%"> <a href="/embed.yaws">Embedding Yaws</a></div>
<div class="%%upload0%%"> <a href="/upload0.yaws">File upload</a> </div>
<div class="%%form%%"> <a href="/form.yaws">Forms</a> </div>
<div class="%%haxe_intro%%"> <a href="/haxe_intro.yaws">haXe remoting</a></div>
<div class="%%pcookie%%"> <a href="/pcookie.yaws">Persistent Cookies</a> </div>
<div class="%%query%%"> <a href="/query.yaws">Query part of url</a></div>
<div class="%%redirect%%"> <a href="/redirect.yaws">Redirect</a> </div>
<div class="%%ssi%%"> <a href="/ssi.yaws">Server side includes</a> </div>
<div class="%%simple%%"> <a href="/simple.yaws">Simple</a> </div>
<div class="%%soap_intro%%"> <a href="/soap_intro.yaws">SOAP with Yaws</a></div>
<div class="%%stream%%"> <a href="/stream.yaws">Streaming data</a> </div>
<div class="%%websockets%%"> <a href="/websockets.yaws">Web Sockets</a> </div>
<a href="/shoppingcart/index.yaws">Tiny shopping cart</a>
<div class="%%yapp_intro%%"> <a href="/yapp_intro.yaws">Yaws applications</a></div>

<h4> Misc </h4>
<div class="%%internals%%"> <a href="/internals.yaws">Internals</a> </div>



</div>




