#!/bin/sh


prefix=$1
erl=$2
etcdir=$3

. ../vsn.mk
y=yaws-${YAWS_VSN}


sh ./mangle ${prefix}/lib/yaws ${erl} yaws.ss ${prefix}/bin/yaws
install -d ${prefix}/lib/yaws/examples/ebin
install -d ${prefix}/lib/yaws/examples/include
chmod +x ${prefix}/bin/yaws
if [ -f ${etcdir}/yaws.conf ]; then
   t=${etcdir}/yaws.conf.template
else
   t=${etcdir}/yaws.conf
fi

sh ./mangle ${prefix}/lib/yaws ${erl} yaws.conf.template ${t}


if [ -f /etc/gentoo-release ]; then
    install -d  ${etcdir}/init.d/
    install -d ${etcdir}/conf.d/
    cp gentoo/init.d.yaws  ${etcdir}/init.d/yaws
    chmod +x ${etcdir}/init.d/yaws
    cp gentoo/conf.d.yaws ${etcdir}/conf.d/yaws

elif [ -f /etc/redhat-release ]; then
    install -d ${etcdir}/init.d
    cp yaws.init.d ${etcdir}/init.d/yaws
    chmod +x ${etcdir}/init.d/yaws
else
    echo "Don't know how to make /etc/init scrips for this system"
fi




