#!/bin/sh

set -x

. ../vsn.mk
CVS_RSH=ssh
Y=`echo ${YAWS_VSN} | sed 's/\./-/g'`
cd ../..

cvs tag -F yaws-${Y}

rm -rf tmp 2> /dev/null
mkdir tmp

cvs export -d tmp -r yaws-$Y .
cd tmp
mv yaws yaws-${YAWS_VSN}
ln -s yaws-${YAWS_VSN} yaws
tar cfz  yaws-${YAWS_VSN}.tar.gz yaws  yaws-${YAWS_VSN}
mv yaws-${YAWS_VSN}.tar.gz ..
cd ..
echo release `pwd`/yaws-${YAWS_VSN}.tar.gz 



