#!/bin/sh

#set -x

# determine absolute path to source dir root
srctree="$(cd $(dirname "$0") && cd .. && pwd)"

# change to scripts dir (or wherever this script resides)
cd "$(dirname "$0")"

. ../vsn.mk

echo packing release ${YAWS_VSN} 

Y=`echo ${YAWS_VSN} | sed 's/\./-/g'`
TAG="yaws-${Y}"
NAME_VERSION="yaws-${YAWS_VSN}"

if [ ! -f ./make-release ]; then
    echo "need to be in scripts dir"; exit 1;
fi

(cd ../win32; make clean all)
cd ../..



# Add/update release tag
#cvs tag -F yaws-${Y}
svn delete https://erlyaws.svn.sourceforge.net/svnroot/erlyaws/tags/$TAG -m ""  2> /dev/null
svn copy https://erlyaws.svn.sourceforge.net/svnroot/erlyaws/trunk/ https://erlyaws.svn.sourceforge.net/svnroot/erlyaws/tags/$TAG -m "version ${Y}"

# Create release .tar.gz of sources
# (including symlink yaws -> $NAME_VERSION)
rm -rf tmp 2> /dev/null
mkdir tmp
cd tmp
svn export https://erlyaws.svn.sourceforge.net/svnroot/erlyaws/trunk
cd trunk
mv yaws "$NAME_VERSION"
ln -s "$NAME_VERSION" yaws
tar cfz "$NAME_VERSION.tar.gz" yaws "$NAME_VERSION"

echo release resides in `pwd`/$NAME_VERSION.tar.gz
echo release resides in `pwd`/win32/Yaws-${YAWS_VSN}-windows-installer.exe

exit 0



