%% HRL file generated by ERLSOM
%%
%% It is possible to change the name of the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.

-record('soap:tAddress', {anyAttribs, 'wsdl:required', 'location'}).
-record('soap:tHeaderFault', {anyAttribs, 'message', 'part', 'use', 'encodingStyle', 'namespace'}).
-record('soap:tHeader', {anyAttribs, 'wsdl:required', 'message', 'part', 'use', 'encodingStyle', 'namespace', 'headerfault'}).
-record('soap:tFault', {anyAttribs, 'wsdl:required', 'parts', 'encodingStyle', 'use', 'namespace', 'name'}).
-record('soap:tFaultRes', {anyAttribs, 'wsdl:required', 'parts', 'encodingStyle', 'use', 'namespace'}).
-record('soap:tBody', {anyAttribs, 'wsdl:required', 'parts', 'encodingStyle', 'use', 'namespace'}).
-record('soap:tOperation', {anyAttribs, 'wsdl:required', 'soapAction', 'soapActionRequired', 'style'}).
-record('soap:tBinding', {anyAttribs, 'wsdl:required', 'transport', 'style'}).
-record('soap:tExtensibilityElementOpenAttrs', {anyAttribs, 'wsdl:required'}).
-record('wsdl:tDocumentation', {anyAttribs, choice}).
-record('wsdl:tDocumented', {anyAttribs, 'documentation'}).
-record('wsdl:tExtensibleAttributesDocumented', {anyAttribs, 'documentation'}).
-record('wsdl:tExtensibleDocumented', {anyAttribs, 'documentation', choice}).
-record('wsdl:anyTopLevelOptionalElement', {anyAttribs, choice}).
-record('wsdl:tDefinitions', {anyAttribs, 'targetNamespace', 'name', 'documentation', choice, choice1}).
-record('wsdl:tImport', {anyAttribs, 'namespace', 'location', 'documentation'}).
-record('wsdl:tTypes', {anyAttribs, 'documentation', choice}).
-record('wsdl:tMessage', {anyAttribs, 'name', 'documentation', choice, 'part'}).
-record('wsdl:tPart', {anyAttribs, 'name', 'element', 'type', 'documentation'}).
-record('wsdl:tPortType', {anyAttribs, 'name', 'documentation', 'operation'}).
-record('wsdl:tOperation', {anyAttribs, 'name', 'parameterOrder', 'documentation', choice, choice1}).
-record('wsdl:request-response-or-one-way-operation/SEQ1', {anyAttribs, 'output', 'fault'}).
-record('wsdl:request-response-or-one-way-operation', {anyAttribs, 'input', 'request-response-or-one-way-operation/SEQ1'}).
-record('wsdl:solicit-response-or-notification-operation/SEQ2', {anyAttribs, 'input', 'fault'}).
-record('wsdl:solicit-response-or-notification-operation', {anyAttribs, 'output', 'solicit-response-or-notification-operation/SEQ2'}).
-record('wsdl:tParam', {anyAttribs, 'name', 'message', 'documentation'}).
-record('wsdl:tFault', {anyAttribs, 'name', 'message', 'documentation'}).
-record('wsdl:tBinding', {anyAttribs, 'name', 'type', 'documentation', choice, 'operation'}).
-record('wsdl:tBindingOperationMessage', {anyAttribs, 'name', 'documentation', choice}).
-record('wsdl:tBindingOperationFault', {anyAttribs, 'name', 'documentation', choice}).
-record('wsdl:tBindingOperation', {anyAttribs, 'name', 'documentation', choice, 'input', 'output', 'fault'}).
-record('wsdl:tService', {anyAttribs, 'name', 'documentation', choice, 'port'}).
-record('wsdl:tPort', {anyAttribs, 'name', 'binding', 'documentation', choice}).
-record('wsdl:tExtensibilityElement', {anyAttribs, 'wsdl:required'}).
