<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e9344fa" target="_blank">e9344fa</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e9344fa');">
    prepare for 1.84
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e9344fa');">
    // Claes Wikstrom
  </div>
  <div id="msg-e9344fa" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e9344fa');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jul 5 20:20:13 2009</strong>

prepare for 1.84
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c30ef89" target="_blank">c30ef89</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c30ef89');">
    prepare for 1.84
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c30ef89');">
    // Claes Wikstrom
  </div>
  <div id="msg-c30ef89" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c30ef89');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jul 5 20:06:23 2009</strong>

prepare for 1.84
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4683f85" target="_blank">4683f85</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4683f85');">
    patch from anders abramhamson - a bug with multiprat posts and a head being reversed
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4683f85');">
    // Claes Wikstrom
  </div>
  <div id="msg-4683f85" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4683f85');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jul 5 20:04:27 2009</strong>

patch from anders abramhamson - a bug with multiprat posts and a head being reversed
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5355a13" target="_blank">5355a13</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5355a13');">
    doc
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5355a13');">
    // Claes Wikstrom
  </div>
  <div id="msg-5355a13" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5355a13');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 15:56:51 2009</strong>

doc
    </pre>
  </div>
</div>
