<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9c63c94" target="_blank">9c63c94</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9c63c94');">
    preparing for 1.86
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9c63c94');">
    // Claes Wikstrom
  </div>
  <div id="msg-9c63c94" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9c63c94');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Dec 6 14:49:46 2009</strong>

preparing for 1.86
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2470367" target="_blank">2470367</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2470367');">
    handle expired cookie sessions in the example
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2470367');">
    // Claes Wikstrom
  </div>
  <div id="msg-2470367" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2470367');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Dec 6 14:34:38 2009</strong>

handle expired cookie sessions in the example
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/082f043" target="_blank">082f043</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-082f043');">
    if sendfile hits EOVERFLOW send the file from Erlang code instead
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-082f043');">
    // Steve Vinoski
  </div>
  <div id="msg-082f043" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-082f043');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Dec 5 04:50:13 2009</strong>

if sendfile hits EOVERFLOW send the file from Erlang code instead
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9cee816" target="_blank">9cee816</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9cee816');">
    json binary keys patch by TBBle
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9cee816');">
    // Claes Wikstrom
  </div>
  <div id="msg-9cee816" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9cee816');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Dec 3 09:51:06 2009</strong>

json binary keys patch by TBBle
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b5156f9" target="_blank">b5156f9</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b5156f9');">
    Merge branch 'master' of git://github.com/davide/yaws into davide/master
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b5156f9');">
    // Steve Vinoski
  </div>
  <div id="msg-b5156f9" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b5156f9');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Dec 3 00:50:52 2009</strong>

Merge branch 'master' of git://github.com/davide/yaws into davide/master
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5debb9f" target="_blank">5debb9f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5debb9f');">
    README docs
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5debb9f');">
    // Claes Wikstrom
  </div>
  <div id="msg-5debb9f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5debb9f');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Dec 2 22:14:25 2009</strong>

README docs
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/82a449b" target="_blank">82a449b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-82a449b');">
    Forward prox functionality added through a patch by Colm Dougan
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-82a449b');">
    // Claes Wikstrom
  </div>
  <div id="msg-82a449b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-82a449b');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Dec 2 21:48:51 2009</strong>

Forward prox functionality added through a patch by Colm Dougan
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6055704" target="_blank">6055704</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6055704');">
    patch from anders dahlin to always populate yaws auth headers
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6055704');">
    // Claes Wikstrom
  </div>
  <div id="msg-6055704" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6055704');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Dec 2 17:58:13 2009</strong>

patch from anders dahlin to always populate yaws auth headers
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b30714f" target="_blank">b30714f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b30714f');">
    create configure script at release
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b30714f');">
    // Claes Wikstrom
  </div>
  <div id="msg-b30714f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b30714f');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Dec 2 15:47:16 2009</strong>

create configure script at release
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d3f2242" target="_blank">d3f2242</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d3f2242');">
    Added SSL support to stream_process_* functions.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d3f2242');">
    // davide
  </div>
  <div id="msg-d3f2242" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d3f2242');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Wed Dec 2 15:08:24 2009</strong>

Added SSL support to stream_process_* functions.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2ed6733" target="_blank">2ed6733</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2ed6733');">
    Added support for passing SSL configurations to start_embedded as a proplist (passing #ssl{} still works).
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2ed6733');">
    // davide
  </div>
  <div id="msg-2ed6733" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2ed6733');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Tue Dec 1 14:08:28 2009</strong>

Added support for passing SSL configurations to start_embedded as a proplist (passing #ssl{} still works).
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ab5675f" target="_blank">ab5675f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ab5675f');">
    Fixed Issue #27
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ab5675f');">
    // Claes Wikstrom
  </div>
  <div id="msg-ab5675f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ab5675f');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Dec 1 12:09:56 2009</strong>

Fixed Issue #27
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b7656de" target="_blank">b7656de</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b7656de');">
    Added support for excluding dirs from an appmod. This is useful for / appmods
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b7656de');">
    // Claes Wikstrom
  </div>
  <div id="msg-b7656de" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b7656de');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Nov 30 00:04:36 2009</strong>

Added support for excluding dirs from an appmod. This is useful for / appmods
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a7ee64c" target="_blank">a7ee64c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a7ee64c');">
    clean target
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a7ee64c');">
    // Claes Wikstrom
  </div>
  <div id="msg-a7ee64c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a7ee64c');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Nov 29 22:45:02 2009</strong>

clean target
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b43bc52" target="_blank">b43bc52</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b43bc52');">
    compile error , at least on older erls
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b43bc52');">
    // Claes Wikstrom
  </div>
  <div id="msg-b43bc52" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b43bc52');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Nov 29 22:00:12 2009</strong>

compile error , at least on older erls
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/323c10e" target="_blank">323c10e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-323c10e');">
    erasing the connection header must also set doclose to false
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-323c10e');">
    // Steve Vinoski
  </div>
  <div id="msg-323c10e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-323c10e');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Nov 23 15:37:36 2009</strong>

erasing the connection header must also set doclose to false
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c32479a" target="_blank">c32479a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c32479a');">
    add explanation about global setting: soap_srv_mods to man file: yaws.conf.5
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c32479a');">
    // Eric Liang
  </div>
  <div id="msg-c32479a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c32479a');">
    <pre>
<strong>Author: Eric Liang &lt;eric.l.2046@gmail.com&gt;</strong>
<strong>Date:   Fri Nov 20 16:30:27 2009</strong>

add explanation about global setting: soap_srv_mods to man file: yaws.conf.5
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/58a4471" target="_blank">58a4471</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-58a4471');">
    get back the start_link/0 in yaws_soap_srv.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-58a4471');">
    // Eric Liang
  </div>
  <div id="msg-58a4471" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-58a4471');">
    <pre>
<strong>Author: Eric Liang &lt;eric.l.2046@gmail.com&gt;</strong>
<strong>Date:   Fri Nov 20 14:37:03 2009</strong>

get back the start_link/0 in yaws_soap_srv.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/813f032" target="_blank">813f032</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-813f032');">
    support on addtional specified prefix when rpc call by method: yaws_soap_lib:call.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-813f032');">
    // Eric Liang
  </div>
  <div id="msg-813f032" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-813f032');">
    <pre>
<strong>Author: Eric Liang &lt;eric.l.2046@gmail.com&gt;</strong>
<strong>Date:   Fri Nov 20 07:43:52 2009</strong>

support on addtional specified prefix when rpc call by method: yaws_soap_lib:call.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d8df08c" target="_blank">d8df08c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d8df08c');">
    add the soap_srv_mods support, which can setup soap serve modules while yaws start.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d8df08c');">
    // Eric Liang
  </div>
  <div id="msg-d8df08c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d8df08c');">
    <pre>
<strong>Author: Eric Liang &lt;eric.l.2046@gmail.com&gt;</strong>
<strong>Date:   Thu Nov 19 14:36:57 2009</strong>

add the soap_srv_mods support, which can setup soap serve modules while yaws start.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ded4870" target="_blank">ded4870</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ded4870');">
    remove duplicate set_dyn_headers line from php handle_ut case
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ded4870');">
    // Steve Vinoski
  </div>
  <div id="msg-ded4870" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ded4870');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Nov 21 22:41:32 2009</strong>

remove duplicate set_dyn_headers line from php handle_ut case
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f48d782" target="_blank">f48d782</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f48d782');">
    Merge branch 'master' of git://github.com/etnt/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f48d782');">
    // Claes Wikstrom
  </div>
  <div id="msg-f48d782" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f48d782');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Nov 16 15:55:25 2009</strong>

Merge branch 'master' of git://github.com/etnt/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5e3b650" target="_blank">5e3b650</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5e3b650');">
    Added 'autoconf' as needed when building from a fresh clone.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5e3b650');">
    // Torbjorn Tornkvist
  </div>
  <div id="msg-5e3b650" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5e3b650');">
    <pre>
<strong>Author: Torbjorn Tornkvist &lt;tobbe@bult.hq.kred&gt;</strong>
<strong>Date:   Mon Nov 16 12:58:02 2009</strong>

Added 'autoconf' as needed when building from a fresh clone.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5c5c36b" target="_blank">5c5c36b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5c5c36b');">
    prevent crash caused by malicious client sending an empty Host header
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5c5c36b');">
    // Steve Vinoski
  </div>
  <div id="msg-5c5c36b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5c5c36b');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Nov 13 00:46:20 2009</strong>

prevent crash caused by malicious client sending an empty Host header
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/189188b" target="_blank">189188b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-189188b');">
    rm configure
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-189188b');">
    // Claes Wikstrom
  </div>
  <div id="msg-189188b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-189188b');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Nov 11 22:43:42 2009</strong>

rm configure
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/48c117d" target="_blank">48c117d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-48c117d');">
    Add example for haXe returning an error object
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-48c117d');">
    // Paul Hampson
  </div>
  <div id="msg-48c117d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-48c117d');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 09:04:07 2009</strong>

Add example for haXe returning an error object
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/08d6c0d" target="_blank">08d6c0d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-08d6c0d');">
    Merge branch 'haxe-remoting-fixes' into rpc-error-responses
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-08d6c0d');">
    // Paul Hampson
  </div>
  <div id="msg-08d6c0d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-08d6c0d');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 09:11:57 2009</strong>

Merge branch 'haxe-remoting-fixes' into rpc-error-responses
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5316274" target="_blank">5316274</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5316274');">
    Document how to run haXe remoting sample under neko
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5316274');">
    // Paul Hampson
  </div>
  <div id="msg-5316274" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5316274');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 09:08:04 2009</strong>

Document how to run haXe remoting sample under neko

This is probably obvious to a regular or occasional haXe user, but
invaluable to someone who's only using haXe to ensure his yaws_rpc
changes are valid...
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b503fa4" target="_blank">b503fa4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b503fa4');">
    Export haXe remoting handler function
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b503fa4');">
    // Paul Hampson
  </div>
  <div id="msg-b503fa4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b503fa4');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 09:01:53 2009</strong>

Export haXe remoting handler function
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b10354c" target="_blank">b10354c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b10354c');">
    Update haxe remoting sample to current remoting API
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b10354c');">
    // Paul Hampson
  </div>
  <div id="msg-b10354c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b10354c');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 09:00:02 2009</strong>

Update haxe remoting sample to current remoting API
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/af707a9" target="_blank">af707a9</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-af707a9');">
    Add example for JSON-RPC returning an error object
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-af707a9');">
    // Paul Hampson
  </div>
  <div id="msg-af707a9" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-af707a9');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 08:03:55 2009</strong>

Add example for JSON-RPC returning an error object

A real object could be used as well as a string here, but jsolait
as bundled stringifies the object when it raises a JSONRPCError
exception.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/908fea6" target="_blank">908fea6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-908fea6');">
    Allow JSON-RPC/haXe remoting handlers to send error objects
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-908fea6');">
    // Paul Hampson
  </div>
  <div id="msg-908fea6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-908fea6');">
    <pre>
<strong>Author: Paul Hampson &lt;paulh@microforte.com&gt;</strong>
<strong>Date:   Mon Nov 9 07:10:11 2009</strong>

Allow JSON-RPC/haXe remoting handlers to send error objects

Any hander which may return a payload of { response, ErlStruct }
can also send { error, ErlStruct } to have the object described
in ErlStruct sent back as an error or exception depending on the
RPC protocol in use.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e126213" target="_blank">e126213</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e126213');">
    minor code clarity and indentation change
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e126213');">
    // Steve Vinoski
  </div>
  <div id="msg-e126213" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e126213');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Nov 6 04:30:47 2009</strong>

minor code clarity and indentation change
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6752f93" target="_blank">6752f93</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6752f93');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6752f93');">
    // Claes Wikstrom
  </div>
  <div id="msg-6752f93" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6752f93');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Nov 5 19:24:54 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b0feb46" target="_blank">b0feb46</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b0feb46');">
    docs bug
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b0feb46');">
    // Claes Wikstrom
  </div>
  <div id="msg-b0feb46" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b0feb46');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Nov 5 19:24:38 2009</strong>

docs bug
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9cd3e6e" target="_blank">9cd3e6e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9cd3e6e');">
    Fixed http://github.com/klacke/yaws/issues/unreads#issue/22
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9cd3e6e');">
    // Claes Wikstrom
  </div>
  <div id="msg-9cd3e6e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9cd3e6e');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Nov 4 19:59:51 2009</strong>

Fixed http://github.com/klacke/yaws/issues/unreads#issue/22
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b8c1de1" target="_blank">b8c1de1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b8c1de1');">
    Allow binaries as json values.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b8c1de1');">
    // Matt Stancliff
  </div>
  <div id="msg-b8c1de1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b8c1de1');">
    <pre>
<strong>Author: Matt Stancliff &lt;matt@genges.com&gt;</strong>
<strong>Date:   Wed Nov 4 07:16:01 2009</strong>

Allow binaries as json values.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6144b4f" target="_blank">6144b4f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6144b4f');">
    mkcert
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6144b4f');">
    // Claes Wikstrom
  </div>
  <div id="msg-6144b4f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6144b4f');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Oct 18 15:54:55 2009</strong>

mkcert
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/aa94e0a" target="_blank">aa94e0a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-aa94e0a');">
    Merge branch 'auth' of git://github.com/faal/yaws into faal
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-aa94e0a');">
    // Torbjorn Tornkvist
  </div>
  <div id="msg-aa94e0a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-aa94e0a');">
    <pre>
<strong>Author: Torbjorn Tornkvist &lt;tobbe@tornkvist.org&gt;</strong>
<strong>Date:   Mon Apr 20 13:37:19 2009</strong>

Merge branch 'auth' of git://github.com/faal/yaws into faal
    </pre>
  </div>
</div>
