<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/229c5b6" target="_blank">229c5b6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-229c5b6');">
    prepare for 1.85
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-229c5b6');">
    // Claes Wikstrom
  </div>
  <div id="msg-229c5b6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-229c5b6');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sat Oct 17 23:07:14 2009</strong>

prepare for 1.85
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2534ca7" target="_blank">2534ca7</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2534ca7');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2534ca7');">
    // Steve Vinoski
  </div>
  <div id="msg-2534ca7" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2534ca7');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Oct 17 21:34:33 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/18cec55" target="_blank">18cec55</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-18cec55');">
    fixes for FCGI authorization (Bruno Rijsman), plus I cleaned up indentation and comments in yaws_cgi.erl
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-18cec55');">
    // Steve Vinoski
  </div>
  <div id="msg-18cec55" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-18cec55');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Oct 17 21:34:10 2009</strong>

fixes for FCGI authorization (Bruno Rijsman), plus I cleaned up indentation and comments in yaws_cgi.erl
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/682bc96" target="_blank">682bc96</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-682bc96');">
    document yaws_multipart (with the assistance of Praveen Ray)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-682bc96');">
    // Steve Vinoski
  </div>
  <div id="msg-682bc96" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-682bc96');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Oct 17 21:09:34 2009</strong>

document yaws_multipart (with the assistance of Praveen Ray)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/68ab570" target="_blank">68ab570</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-68ab570');">
    locale setting
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-68ab570');">
    // Claes Wikstrom
  </div>
  <div id="msg-68ab570" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-68ab570');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sat Oct 17 20:35:27 2009</strong>

locale setting
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/006dfea" target="_blank">006dfea</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-006dfea');">
    Patch from wde with support for virthosting several ssl serveres on the same IP. This makes sense if we have multiple subjectAltName in the ssl cert
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-006dfea');">
    // Claes Wikstrom
  </div>
  <div id="msg-006dfea" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-006dfea');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Oct 16 21:44:40 2009</strong>

Patch from wde with support for virthosting several ssl serveres on the same IP. This makes sense if we have multiple subjectAltName in the ssl cert
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/16c54f8" target="_blank">16c54f8</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-16c54f8');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-16c54f8');">
    // Claes Wikstrom
  </div>
  <div id="msg-16c54f8" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-16c54f8');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sat Oct 3 22:54:17 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a9ce4a0" target="_blank">a9ce4a0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a9ce4a0');">
    some ssl info
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a9ce4a0');">
    // Claes Wikstrom
  </div>
  <div id="msg-a9ce4a0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a9ce4a0');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sat Oct 3 22:54:05 2009</strong>

some ssl info
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/cebdd43" target="_blank">cebdd43</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-cebdd43');">
    moved yaws_multipart.erl to src, so remove from examples
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-cebdd43');">
    // Steve Vinoski
  </div>
  <div id="msg-cebdd43" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-cebdd43');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Sep 30 15:45:39 2009</strong>

moved yaws_multipart.erl to src, so remove from examples
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6b3f0cc" target="_blank">6b3f0cc</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6b3f0cc');">
    remove commented-out example code from yaws_multipart.erl to use in documentation
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6b3f0cc');">
    // Steve Vinoski
  </div>
  <div id="msg-6b3f0cc" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6b3f0cc');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Sep 30 03:48:41 2009</strong>

remove commented-out example code from yaws_multipart.erl to use in documentation
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4248f8d" target="_blank">4248f8d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4248f8d');">
    move yaws_multipart.erl to src dir and incorporate klacke's changes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4248f8d');">
    // Steve Vinoski
  </div>
  <div id="msg-4248f8d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4248f8d');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Sep 30 03:47:26 2009</strong>

move yaws_multipart.erl to src dir and incorporate klacke's changes
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6adf0e1" target="_blank">6adf0e1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6adf0e1');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6adf0e1');">
    // Steve Vinoski
  </div>
  <div id="msg-6adf0e1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6adf0e1');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 28 20:44:55 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c966d77" target="_blank">c966d77</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c966d77');">
    re-introduce Steves optimazation of fmtnow()
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c966d77');">
    // Claes Wikstrom
  </div>
  <div id="msg-c966d77" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c966d77');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Sep 28 20:35:11 2009</strong>

re-introduce Steves optimazation of fmtnow()
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/887a15a" target="_blank">887a15a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-887a15a');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-887a15a');">
    // Steve Vinoski
  </div>
  <div id="msg-887a15a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-887a15a');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 28 20:03:18 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b605e5c" target="_blank">b605e5c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b605e5c');">
    fixes for yaws_multipart.erl (Praveen Ray)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b605e5c');">
    // Steve Vinoski
  </div>
  <div id="msg-b605e5c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b605e5c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 28 19:58:24 2009</strong>

fixes for yaws_multipart.erl (Praveen Ray)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1c32b52" target="_blank">1c32b52</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1c32b52');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1c32b52');">
    // Claes Wikstrom
  </div>
  <div id="msg-1c32b52" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1c32b52');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Sep 28 11:13:58 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8322cec" target="_blank">8322cec</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8322cec');">
    timezone format patch by Per Hedeland
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8322cec');">
    // Claes Wikstrom
  </div>
  <div id="msg-8322cec" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8322cec');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Sep 28 11:13:39 2009</strong>

timezone format patch by Per Hedeland
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4c90d3a" target="_blank">4c90d3a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4c90d3a');">
    add new multipart example yaws_multipart.erl (Praveen Ray)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4c90d3a');">
    // Steve Vinoski
  </div>
  <div id="msg-4c90d3a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4c90d3a');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 28 05:56:42 2009</strong>

add new multipart example yaws_multipart.erl (Praveen Ray)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/92681ef" target="_blank">92681ef</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-92681ef');">
    fix spelling
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-92681ef');">
    // Steve Vinoski
  </div>
  <div id="msg-92681ef" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-92681ef');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 28 05:55:43 2009</strong>

fix spelling
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5018bcc" target="_blank">5018bcc</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5018bcc');">
    determine gcc flags for 32-bit or 64-bit Erlang on OS X Snow Leopard
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5018bcc');">
    // Steve Vinoski
  </div>
  <div id="msg-5018bcc" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5018bcc');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Sep 26 06:03:04 2009</strong>

determine gcc flags for 32-bit or 64-bit Erlang on OS X Snow Leopard
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/984470b" target="_blank">984470b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-984470b');">
    installer
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-984470b');">
    // Claes Wikstrom
  </div>
  <div id="msg-984470b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-984470b');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Sep 22 22:07:17 2009</strong>

installer
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d5676b2" target="_blank">d5676b2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d5676b2');">
    Auth enhancements by Anders Dahlin, - Auth - unauthorized enhancements - Setup auth rewrite/cleanup - (Embedded) Config enhancements
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d5676b2');">
    // Claes Wikstrom
  </div>
  <div id="msg-d5676b2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d5676b2');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Sep 22 12:57:20 2009</strong>

Auth enhancements by Anders Dahlin,
- Auth - unauthorized enhancements
- Setup auth rewrite/cleanup
- (Embedded) Config enhancements
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/aa32fa0" target="_blank">aa32fa0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-aa32fa0');">
    document streamcontent process delivery functions
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-aa32fa0');">
    // Steve Vinoski
  </div>
  <div id="msg-aa32fa0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-aa32fa0');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 21 16:33:49 2009</strong>

document streamcontent process delivery functions
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3a6c4c2" target="_blank">3a6c4c2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3a6c4c2');">
    document yaws --nodebug option
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3a6c4c2');">
    // Steve Vinoski
  </div>
  <div id="msg-3a6c4c2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3a6c4c2');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 21 16:33:48 2009</strong>

document yaws --nodebug option
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a80cfee" target="_blank">a80cfee</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a80cfee');">
    add --nodebug option
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a80cfee');">
    // Steve Vinoski
  </div>
  <div id="msg-a80cfee" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a80cfee');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Sep 21 16:33:03 2009</strong>

add --nodebug option
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d5c2210" target="_blank">d5c2210</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d5c2210');">
    Merge branch 'master' of git://github.com/davide/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d5c2210');">
    // Claes Wikstrom
  </div>
  <div id="msg-d5c2210" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d5c2210');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sat Sep 19 21:33:46 2009</strong>

Merge branch 'master' of git://github.com/davide/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/913aff8" target="_blank">913aff8</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-913aff8');">
    Use iolists instead of binaries for streamcontent_from_pid data, and add a new test for the streamcontent_from_pid feature
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-913aff8');">
    // Steve Vinoski
  </div>
  <div id="msg-913aff8" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-913aff8');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Sep 19 21:29:15 2009</strong>

Use iolists instead of binaries for streamcontent_from_pid data, and
add a new test for the streamcontent_from_pid feature
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6d8d382" target="_blank">6d8d382</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6d8d382');">
    Fixed support for Timeout=infinity in streamcontent_with_timeout.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6d8d382');">
    // davide
  </div>
  <div id="msg-6d8d382" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6d8d382');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Sat Sep 19 12:59:57 2009</strong>

Fixed support for Timeout=infinity in streamcontent_with_timeout.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5f35f5b" target="_blank">5f35f5b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5f35f5b');">
    add streamcontent_from_pid capability to allow direct streaming to socket
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5f35f5b');">
    // Steve Vinoski
  </div>
  <div id="msg-5f35f5b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5f35f5b');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Sep 19 05:33:06 2009</strong>

add streamcontent_from_pid capability to allow direct streaming to socket
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/0efd59c" target="_blank">0efd59c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-0efd59c');">
    more efficient check for the yaws application being up
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-0efd59c');">
    // Steve Vinoski
  </div>
  <div id="msg-0efd59c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-0efd59c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Sep 17 20:17:02 2009</strong>

more efficient check for the yaws application being up
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/51cbdc0" target="_blank">51cbdc0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-51cbdc0');">
    fix dumb errors in previous commit
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-51cbdc0');">
    // Steve Vinoski
  </div>
  <div id="msg-51cbdc0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-51cbdc0');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Sep 10 02:52:11 2009</strong>

fix dumb errors in previous commit
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f2e687f" target="_blank">f2e687f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f2e687f');">
    fix decode_base64 to return just a tuple in case of error (reported by Gabriel Ki)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f2e687f');">
    // Steve Vinoski
  </div>
  <div id="msg-f2e687f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f2e687f');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Sep 9 22:11:49 2009</strong>

fix decode_base64 to return just a tuple in case of error (reported by Gabriel Ki)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/12ddebc" target="_blank">12ddebc</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-12ddebc');">
    fix HTTP header case sensitivity problem in yaws_cgi (Bruno Rijsman)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-12ddebc');">
    // Steve Vinoski
  </div>
  <div id="msg-12ddebc" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-12ddebc');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Sep 8 16:31:25 2009</strong>

fix HTTP header case sensitivity problem in yaws_cgi (Bruno Rijsman)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4b3bbeb" target="_blank">4b3bbeb</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4b3bbeb');">
    move join function to yaws:join_sep
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4b3bbeb');">
    // Steve Vinoski
  </div>
  <div id="msg-4b3bbeb" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4b3bbeb');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Sep 8 16:30:42 2009</strong>

move join function to yaws:join_sep
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2e6b7f4" target="_blank">2e6b7f4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2e6b7f4');">
    reduce loop to 5 for sendfile_get test
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2e6b7f4');">
    // Steve Vinoski
  </div>
  <div id="msg-2e6b7f4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2e6b7f4');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Sep 8 16:28:04 2009</strong>

reduce loop to 5 for sendfile_get test
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c3a8eb2" target="_blank">c3a8eb2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c3a8eb2');">
    cleanup
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c3a8eb2');">
    // Claes Wikstrom
  </div>
  <div id="msg-c3a8eb2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c3a8eb2');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@rock.(none)&gt;</strong>
<strong>Date:   Tue Aug 25 23:32:04 2009</strong>

cleanup
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b752b8c" target="_blank">b752b8c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b752b8c');">
    trivial edit cleanups
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b752b8c');">
    // Steve Vinoski
  </div>
  <div id="msg-b752b8c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b752b8c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Aug 22 15:35:52 2009</strong>

trivial edit cleanups
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f65b422" target="_blank">f65b422</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f65b422');">
    More work by Ander Dahlin to pass the Realm in case of faile auth to the authmod
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f65b422');">
    // Claes Wikstrom
  </div>
  <div id="msg-f65b422" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f65b422');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Aug 21 15:42:26 2009</strong>

More work by Ander Dahlin to pass the Realm in case of faile auth to the authmod
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/36109e0" target="_blank">36109e0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-36109e0');">
    patch from Anders Dahlin to add errormod_301 till yaws:setup_sconf/3
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-36109e0');">
    // Claes Wikstrom
  </div>
  <div id="msg-36109e0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-36109e0');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Aug 20 21:58:38 2009</strong>

patch from Anders Dahlin to add errormod_301 till yaws:setup_sconf/3
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b39a6fe" target="_blank">b39a6fe</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b39a6fe');">
    several nice cleanups by Anders Dahlin
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b39a6fe');">
    // Claes Wikstrom
  </div>
  <div id="msg-b39a6fe" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b39a6fe');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Aug 20 21:55:50 2009</strong>

several nice cleanups by Anders Dahlin
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/cf6ae42" target="_blank">cf6ae42</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-cf6ae42');">
    stopping yaws_sendfile thru supervisor does not hang - by ks
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-cf6ae42');">
    // Claes Wikstrom
  </div>
  <div id="msg-cf6ae42" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-cf6ae42');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Aug 20 21:49:39 2009</strong>

stopping yaws_sendfile thru supervisor does not hang - by ks
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b71da7e" target="_blank">b71da7e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b71da7e');">
    cleanup
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b71da7e');">
    // Claes Wikstrom
  </div>
  <div id="msg-b71da7e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b71da7e');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Aug 19 21:08:34 2009</strong>

cleanup
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/043ce4e" target="_blank">043ce4e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-043ce4e');">
    invoke handle crash_msg if Mod:auth/2 crashes.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-043ce4e');">
    // Claes Wikstrom
  </div>
  <div id="msg-043ce4e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-043ce4e');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Aug 19 21:07:40 2009</strong>

invoke handle crash_msg if Mod:auth/2 crashes.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/792697b" target="_blank">792697b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-792697b');">
    possible bug with id check
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-792697b');">
    // Claes Wikstrom
  </div>
  <div id="msg-792697b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-792697b');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Aug 19 14:48:41 2009</strong>

possible bug with id check
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/536d65c" target="_blank">536d65c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-536d65c');">
    80 chars row cleanup
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-536d65c');">
    // Claes Wikstrom
  </div>
  <div id="msg-536d65c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-536d65c');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Aug 19 11:33:52 2009</strong>

80 chars row cleanup
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4df0d77" target="_blank">4df0d77</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4df0d77');">
    config of partial_post_size = nolimit was broken
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4df0d77');">
    // Claes Wikstrom
  </div>
  <div id="msg-4df0d77" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4df0d77');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Aug 19 11:32:53 2009</strong>

config of partial_post_size = nolimit was broken
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d9c2d32" target="_blank">d9c2d32</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d9c2d32');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d9c2d32');">
    // Steve Vinoski
  </div>
  <div id="msg-d9c2d32" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d9c2d32');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Aug 17 22:59:43 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/61b1e10" target="_blank">61b1e10</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-61b1e10');">
    updated mime.types from recent Apache web server sources
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-61b1e10');">
    // Steve Vinoski
  </div>
  <div id="msg-61b1e10" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-61b1e10');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Aug 17 22:59:01 2009</strong>

updated mime.types from recent Apache web server sources
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1ba9770" target="_blank">1ba9770</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1ba9770');">
    small fixed by anders dahlin
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1ba9770');">
    // Claes Wikstrom
  </div>
  <div id="msg-1ba9770" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1ba9770');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Aug 17 22:49:20 2009</strong>

small fixed by anders dahlin
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/53608c3" target="_blank">53608c3</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-53608c3');">
    max number of connections patch by Kinoshita
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-53608c3');">
    // Claes Wikstrom
  </div>
  <div id="msg-53608c3" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-53608c3');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Aug 17 22:36:38 2009</strong>

max number of connections patch by Kinoshita
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5ec7807" target="_blank">5ec7807</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5ec7807');">
    check for toolchain
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5ec7807');">
    // Claes Wikstrom
  </div>
  <div id="msg-5ec7807" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5ec7807');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Aug 6 21:48:28 2009</strong>

check for toolchain
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/0e07576" target="_blank">0e07576</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-0e07576');">
    check for toolchain
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-0e07576');">
    // Claes Wikstrom
  </div>
  <div id="msg-0e07576" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-0e07576');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Aug 6 21:43:46 2009</strong>

check for toolchain
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/cb07393" target="_blank">cb07393</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-cb07393');">
    streamcontent_with_timeout bug , git issue #16 fixed
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-cb07393');">
    // Claes Wikstrom
  </div>
  <div id="msg-cb07393" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-cb07393');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Aug 6 13:13:42 2009</strong>

streamcontent_with_timeout bug , git issue #16 fixed
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/45b45ce" target="_blank">45b45ce</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-45b45ce');">
    rm vdir
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-45b45ce');">
    // Claes Wikstrom
  </div>
  <div id="msg-45b45ce" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-45b45ce');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Aug 3 13:40:34 2009</strong>

rm vdir
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/316bf6d" target="_blank">316bf6d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-316bf6d');">
    small fixes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-316bf6d');">
    // Claes Wikstrom
  </div>
  <div id="msg-316bf6d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-316bf6d');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Aug 3 13:22:30 2009</strong>

small fixes
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e5dbee8" target="_blank">e5dbee8</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e5dbee8');">
    readme docs
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e5dbee8');">
    // Claes Wikstrom
  </div>
  <div id="msg-e5dbee8" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e5dbee8');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Aug 3 13:07:55 2009</strong>

readme docs
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/977c123" target="_blank">977c123</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-977c123');">
    1. Fix redirect bug reported by James Lee. 2. Add new regression test for redirect bug. Test details suggested by James Lee. 3. Clean up a bunch of other tests to make them more reliable. Added use of    .PHONY targets for tests, and made tests start and stop Yaws individually.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-977c123');">
    // Steve Vinoski
  </div>
  <div id="msg-977c123" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-977c123');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Aug 2 07:47:51 2009</strong>

1. Fix redirect bug reported by James Lee.
2. Add new regression test for redirect bug. Test details suggested by James Lee.
3. Clean up a bunch of other tests to make them more reliable. Added use of
   .PHONY targets for tests, and made tests start and stop Yaws individually.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/60e5235" target="_blank">60e5235</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-60e5235');">
    correct fcgi calls to use yaws_cgi module
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-60e5235');">
    // Steve Vinoski
  </div>
  <div id="msg-60e5235" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-60e5235');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jul 17 22:48:02 2009</strong>

correct fcgi calls to use yaws_cgi module
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/74b7a81" target="_blank">74b7a81</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-74b7a81');">
    fcgi merger error
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-74b7a81');">
    // Claes Wikstrom
  </div>
  <div id="msg-74b7a81" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-74b7a81');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 10 14:28:35 2009</strong>

fcgi merger error
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2fa66b0" target="_blank">2fa66b0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2fa66b0');">
    cgi support
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2fa66b0');">
    // Claes Wikstrom
  </div>
  <div id="msg-2fa66b0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2fa66b0');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 10 14:26:00 2009</strong>

cgi support
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/034faa4" target="_blank">034faa4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-034faa4');">
    fix setconf call for start_embedded
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-034faa4');">
    // Steve Vinoski
  </div>
  <div id="msg-034faa4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-034faa4');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Jul 6 00:27:36 2009</strong>

fix setconf call for start_embedded
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3655d57" target="_blank">3655d57</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3655d57');">
    eunit test added
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3655d57');">
    // Claes Wikstrom
  </div>
  <div id="msg-3655d57" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3655d57');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jul 5 20:49:32 2009</strong>

eunit test added
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8913f68" target="_blank">8913f68</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8913f68');">
    eunit test added
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8913f68');">
    // Claes Wikstrom
  </div>
  <div id="msg-8913f68" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8913f68');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jul 5 20:49:24 2009</strong>

eunit test added
    </pre>
  </div>
</div>
