<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3a590cb" target="_blank">3a590cb</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3a590cb');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3a590cb');">
    // Claes Wikstrom
  </div>
  <div id="msg-3a590cb" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3a590cb');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 23:05:44 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d983f7d" target="_blank">d983f7d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d983f7d');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d983f7d');">
    // Claes Wikstrom
  </div>
  <div id="msg-d983f7d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d983f7d');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 23:03:12 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/08933df" target="_blank">08933df</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-08933df');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-08933df');">
    // Claes Wikstrom
  </div>
  <div id="msg-08933df" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-08933df');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 22:54:33 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e1e92fc" target="_blank">e1e92fc</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e1e92fc');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e1e92fc');">
    // Claes Wikstrom
  </div>
  <div id="msg-e1e92fc" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e1e92fc');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 21:12:01 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e71db24" target="_blank">e71db24</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e71db24');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e71db24');">
    // Claes Wikstrom
  </div>
  <div id="msg-e71db24" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e71db24');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 20:59:55 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5e1d1ec" target="_blank">5e1d1ec</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5e1d1ec');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5e1d1ec');">
    // Claes Wikstrom
  </div>
  <div id="msg-5e1d1ec" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5e1d1ec');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 20:26:31 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3fd7044" target="_blank">3fd7044</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3fd7044');">
    add date header to OPTIONS response
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3fd7044');">
    // Steve Vinoski
  </div>
  <div id="msg-3fd7044" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3fd7044');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat May 23 05:58:22 2009</strong>

add date header to OPTIONS response
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1025b24" target="_blank">1025b24</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1025b24');">
    fix badmatch calling yaws_server:suffix_type from yaw_server:do_url_type when dav is true
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1025b24');">
    // Steve Vinoski
  </div>
  <div id="msg-1025b24" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1025b24');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri May 22 21:55:23 2009</strong>

fix badmatch calling yaws_server:suffix_type from yaw_server:do_url_type when dav is true
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/19afa9f" target="_blank">19afa9f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-19afa9f');">
    Added fix and tests for github issue #2. Handle zero values for max_num_cached_files, max_num_cached_bytes, and max_size_cached_file to prevent infinite loops.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-19afa9f');">
    // Steve Vinoski
  </div>
  <div id="msg-19afa9f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-19afa9f');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri May 22 08:31:15 2009</strong>

Added fix and tests for github issue #2. Handle zero values for
max_num_cached_files, max_num_cached_bytes, and max_size_cached_file
to prevent infinite loops.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f848506" target="_blank">f848506</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f848506');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f848506');">
    // Steve Vinoski
  </div>
  <div id="msg-f848506" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f848506');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed May 20 19:50:29 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d0e776f" target="_blank">d0e776f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d0e776f');">
    modify time_to_string to avoid slow io_lib:format
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d0e776f');">
    // Steve Vinoski
  </div>
  <div id="msg-d0e776f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d0e776f');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed May 20 19:49:52 2009</strong>

modify time_to_string to avoid slow io_lib:format
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/29dcd07" target="_blank">29dcd07</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-29dcd07');">
    removed obsolete stats collector
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-29dcd07');">
    // Claes Wikstrom
  </div>
  <div id="msg-29dcd07" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-29dcd07');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue May 19 20:04:56 2009</strong>

removed obsolete stats collector
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/15801d7" target="_blank">15801d7</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-15801d7');">
    comment in code
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-15801d7');">
    // Claes Wikstrom
  </div>
  <div id="msg-15801d7" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-15801d7');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon May 4 21:58:14 2009</strong>

comment in code
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/df7a68b" target="_blank">df7a68b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-df7a68b');">
    set HOME if unset, this is required since some distros don't set HOME for code run under/etc/rc and erlexec requires HOME to be set
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-df7a68b');">
    // Claes Wikstrom
  </div>
  <div id="msg-df7a68b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-df7a68b');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon May 4 19:44:17 2009</strong>

set HOME if unset, this is required since some distros don't set HOME for code run under/etc/rc and erlexec requires HOME to be set
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/7d9f3ab" target="_blank">7d9f3ab</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-7d9f3ab');">
    add extra cgi vars patch from joe_e_e
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-7d9f3ab');">
    // Claes Wikstrom
  </div>
  <div id="msg-7d9f3ab" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-7d9f3ab');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon May 4 09:27:40 2009</strong>

add extra cgi vars patch from joe_e_e
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8c1f224" target="_blank">8c1f224</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8c1f224');">
    doc fix by hun
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8c1f224');">
    // Claes Wikstrom
  </div>
  <div id="msg-8c1f224" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8c1f224');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Apr 27 17:35:32 2009</strong>

doc fix by hun
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2d767ad" target="_blank">2d767ad</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2d767ad');">
    new ebuild file from joe_e_e
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2d767ad');">
    // Claes Wikstrom
  </div>
  <div id="msg-2d767ad" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2d767ad');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Apr 27 17:34:09 2009</strong>

new ebuild file from joe_e_e
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f9dd6c0" target="_blank">f9dd6c0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f9dd6c0');">
    patch by joe_e_e to move all files from /etc to /etc/yaws in the installer
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f9dd6c0');">
    // Claes Wikstrom
  </div>
  <div id="msg-f9dd6c0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f9dd6c0');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Apr 27 17:32:59 2009</strong>

patch by joe_e_e to move all files from /etc to /etc/yaws in the installer
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/de056eb" target="_blank">de056eb</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-de056eb');">
    add extra cgi vars patch from joe_e_e
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-de056eb');">
    // Claes Wikstrom
  </div>
  <div id="msg-de056eb" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-de056eb');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Apr 27 17:31:04 2009</strong>

add extra cgi vars patch from joe_e_e
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8ca43c2" target="_blank">8ca43c2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8ca43c2');">
    add extra cgi vars patch from joe_e_e
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8ca43c2');">
    // Claes Wikstrom
  </div>
  <div id="msg-8ca43c2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8ca43c2');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Apr 27 17:22:25 2009</strong>

add extra cgi vars patch from joe_e_e
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b732bd1" target="_blank">b732bd1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b732bd1');">
    doc patch from kevingrimes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b732bd1');">
    // Claes Wikstrom
  </div>
  <div id="msg-b732bd1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b732bd1');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Apr 27 17:20:50 2009</strong>

doc patch from kevingrimes
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8b785f6" target="_blank">8b785f6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8b785f6');">
    Merge branch 'auth' of git@github.com:faal/yaws into auth
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8b785f6');">
    // Fabian Alenius
  </div>
  <div id="msg-8b785f6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8b785f6');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Mon Apr 27 13:16:20 2009</strong>

Merge branch 'auth' of git@github.com:faal/yaws into auth
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/71af10e" target="_blank">71af10e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-71af10e');">
    in open, ensure the gen_server is up before calling it
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-71af10e');">
    // Steve Vinoski
  </div>
  <div id="msg-71af10e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-71af10e');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Apr 26 16:36:39 2009</strong>

in open, ensure the gen_server is up before calling it
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/10febe6" target="_blank">10febe6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-10febe6');">
    added sendfile check for Darwin, since no sendfile is available on OS X Tiger
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-10febe6');">
    // Steve Vinoski
  </div>
  <div id="msg-10febe6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-10febe6');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Apr 25 06:19:00 2009</strong>

added sendfile check for Darwin, since no sendfile is available on OS X Tiger
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/be8d198" target="_blank">be8d198</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-be8d198');">
    fixed compiler warnings for unused variables
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-be8d198');">
    // Steve Vinoski
  </div>
  <div id="msg-be8d198" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-be8d198');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Apr 25 06:17:16 2009</strong>

fixed compiler warnings for unused variables
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8545c2c" target="_blank">8545c2c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8545c2c');">
    document rss_dir
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8545c2c');">
    // Steve Vinoski
  </div>
  <div id="msg-8545c2c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8545c2c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Apr 25 06:12:12 2009</strong>

document rss_dir
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3c41877" target="_blank">3c41877</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3c41877');">
    1. Fixed so that the HTTP status is set to 401 explicitly in yaws_server:handle_ut(...), previously out401 needed to return {status, ...} or status would default to 200.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3c41877');">
    // Fabian Alenius
  </div>
  <div id="msg-3c41877" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3c41877');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian.alenius@gmail.com&gt;</strong>
<strong>Date:   Fri Apr 24 11:36:19 2009</strong>

1. Fixed so that the HTTP status is set to 401 explicitly in
yaws_server:handle_ut(...), previously out401 needed to return
{status, ...} or status would default to 200.

2. Changed outmod:out401(...) so that it returns {ehtml, ...} instead of
{status, ...}

3. Documented the errmormod_401 option in the man page.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f27ca2c" target="_blank">f27ca2c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f27ca2c');">
    minor cleanup modifications
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f27ca2c');">
    // Steve Vinoski
  </div>
  <div id="msg-f27ca2c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f27ca2c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Apr 23 09:27:05 2009</strong>

minor cleanup modifications
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/afea472" target="_blank">afea472</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-afea472');">
    Added ifndef, define to erlsom.h to avoid conflicts
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-afea472');">
    // Fabian Alenius
  </div>
  <div id="msg-afea472" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-afea472');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian.alenius@gmail.com&gt;</strong>
<strong>Date:   Tue Apr 21 17:29:43 2009</strong>

Added ifndef, define to erlsom.h to avoid conflicts
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f44602e" target="_blank">f44602e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f44602e');">
    Merge branch 'master' of git://github.com/klacke/yaws into auth
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f44602e');">
    // Fabian Alenius
  </div>
  <div id="msg-f44602e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f44602e');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian.alenius@gmail.com&gt;</strong>
<strong>Date:   Tue Apr 21 17:04:50 2009</strong>

Merge branch 'master' of git://github.com/klacke/yaws into auth
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3cc5744" target="_blank">3cc5744</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3cc5744');">
    update yapp application version due to yapp_ets_server addition
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3cc5744');">
    // Steve Vinoski
  </div>
  <div id="msg-3cc5744" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3cc5744');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Apr 20 20:52:42 2009</strong>

update yapp application version due to yapp_ets_server addition
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d22255b" target="_blank">d22255b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d22255b');">
    add ets-based yapp registry implementation for cases where mnesia is overkill
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d22255b');">
    // Steve Vinoski
  </div>
  <div id="msg-d22255b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d22255b');">
    <pre>
<strong>Author: Steve Vinoski &lt;svinoski@erlang.verivue.com&gt;</strong>
<strong>Date:   Sat Apr 18 06:16:17 2009</strong>

add ets-based yapp registry implementation for cases where mnesia is overkill
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c1cea99" target="_blank">c1cea99</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c1cea99');">
    Changed the way authentication is done, added support for multiple authentication methods to be used for one directory and changed so that the 401 page can be customized similarly to the 404 page.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c1cea99');">
    // Fabian Alenius
  </div>
  <div id="msg-c1cea99" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c1cea99');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian.alenius@gmail.com&gt;</strong>
<strong>Date:   Thu Apr 16 01:37:28 2009</strong>

Changed the way authentication is done, added support for multiple authentication methods to be used for one directory and changed so that the
401 page can be customized similarly to the 404 page.

1. Renamed yaws_401.erl to yaws_outmod.erl, which is probably a better name considering it's current use(it also displays the crashmsg).
2. Fixed the Makefile accordingly.
2. Changed so that the auth record not only contains the authentication methods but also the headers that should be displayed for the
directory.
3. The headers are added in yaws_config.erl when the config file is parsed, the authmods now has to have a function get_headers/1 that
returns the http headers that are to be displayed.
3. is_auth now goes through the list of directories and when a matching directory is found it calls handle_auth which does the actual
checking.
4. handle_auth checks all the methods specified in the config file, if _one_ returns true, the user is authorized to view the page.
5. Removed deliver_401 and changed so that handle_ut is called with UrlType = unauthorized.
6. Changed handle_ut to handle UrlType = unauthorized, it handles it similarly to when it displays 404. It pulls the errormod_401 from the
GC and calls out401 to display the actual page.
7. Added a function outh_set_auth/1 to yaws.erl which takes a string or a {realm, Realm} tuple and returns the corresponding WWW-Authenticate
header.
8. Fixed so that the headers are displayed when the 401 page is displayed.
9. Removed the special handling of appmod in handle_request. Previously authmods would return appmod when they wanted the 401 page to be
displayed, this is no longer neccessary.
10. Removed the out function from authmod_gssapi.erl.
11. Changed the behaviour of authmod_gssapi so that it simply returns fales when it doesn't find called with the correct headers.
Previously it would crash.

TODO: Add support for multiple authmods and Pam modules for one directory.
Rewrite authmod_gssapi so that it simply returns true or false.
Fix a bug in yaws_ls, it links directories without the final / which means that every time you enter a directory first a 302 page is sent with
a redirect to "dir/".
Properly sort the WWW-authenticate headers, apparently the order mathers. For example Negoiate needs to be above Basic realm for
it to use Negoiate.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f01eff3" target="_blank">f01eff3</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f01eff3');">
    fix overlooked endian issue with socket_fd in set_error_buffer() (thanks to Olivier Girondel)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f01eff3');">
    // Steve Vinoski
  </div>
  <div id="msg-f01eff3" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f01eff3');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Apr 15 01:25:30 2009</strong>

fix overlooked endian issue with socket_fd in set_error_buffer() (thanks to Olivier Girondel)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/0e5ebd2" target="_blank">0e5ebd2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-0e5ebd2');">
    improved checking of --heart-restart arguments
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-0e5ebd2');">
    // Steve Vinoski
  </div>
  <div id="msg-0e5ebd2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-0e5ebd2');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Apr 13 23:00:06 2009</strong>

improved checking of --heart-restart arguments
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2ba5805" target="_blank">2ba5805</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2ba5805');">
    add new --heart-restart option to allow control over heart restarts
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2ba5805');">
    // Steve Vinoski
  </div>
  <div id="msg-2ba5805" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2ba5805');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Apr 13 22:44:47 2009</strong>

add new --heart-restart option to allow control over heart restarts
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6312ad1" target="_blank">6312ad1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6312ad1');">
    very minor indentation fix
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6312ad1');">
    // Steve Vinoski
  </div>
  <div id="msg-6312ad1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6312ad1');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Apr 13 22:44:15 2009</strong>

very minor indentation fix
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/93abf77" target="_blank">93abf77</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-93abf77');">
    modified the way data is passed between yaws_sendfile.erl and the sendfile driver to fix endian problems I found on PPC systems
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-93abf77');">
    // Steve Vinoski
  </div>
  <div id="msg-93abf77" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-93abf77');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Apr 5 22:57:35 2009</strong>

modified the way data is passed between yaws_sendfile.erl and the sendfile driver
to fix endian problems I found on PPC systems
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a3b9ee2" target="_blank">a3b9ee2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a3b9ee2');">
    Remove last occurrence of hyphenated version nums
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a3b9ee2');">
    // Hans Ulrich Niedermann
  </div>
  <div id="msg-a3b9ee2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a3b9ee2');">
    <pre>
<strong>Author: Hans Ulrich Niedermann &lt;hun@n-dimensional.de&gt;</strong>
<strong>Date:   Wed Apr 1 01:51:41 2009</strong>

Remove last occurrence of hyphenated version nums

With CVS or SVN, yaws used release tags like yaws-1-81.
We can just use the version number now with git, though:
yaws-1.81.

Remove the last occurrence of the hyphenated version number.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4635899" target="_blank">4635899</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4635899');">
    apply win32/mkinstaller.sh patch from Hans Ulrich Niedermann
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4635899');">
    // Steve Vinoski
  </div>
  <div id="msg-4635899" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4635899');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Apr 1 02:53:05 2009</strong>

apply win32/mkinstaller.sh patch from Hans Ulrich Niedermann
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f44be6a" target="_blank">f44be6a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f44be6a');">
    all calls to old deprecated guard tests removed
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f44be6a');">
    // Claes Wikstrom
  </div>
  <div id="msg-f44be6a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f44be6a');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Mar 30 23:02:00 2009</strong>

all calls to old deprecated guard tests removed
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ba94b67" target="_blank">ba94b67</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ba94b67');">
    add mime type for MPEG-4 video
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ba94b67');">
    // Steve Vinoski
  </div>
  <div id="msg-ba94b67" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ba94b67');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Mar 28 23:04:31 2009</strong>

add mime type for MPEG-4 video
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6ed3cb4" target="_blank">6ed3cb4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6ed3cb4');">
    configure woes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6ed3cb4');">
    // Claes Wikstrom
  </div>
  <div id="msg-6ed3cb4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6ed3cb4');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Mar 18 17:22:27 2009</strong>

configure woes
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b08c38e" target="_blank">b08c38e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b08c38e');">
    echo push command
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b08c38e');">
    // Claes Wikstrom
  </div>
  <div id="msg-b08c38e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b08c38e');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Mar 18 15:36:52 2009</strong>

echo push command
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8a5d8e7" target="_blank">8a5d8e7</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8a5d8e7');">
    Configure script broken on openbsd due to cygwin weirdness
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8a5d8e7');">
    // Claes Wikstrom
  </div>
  <div id="msg-8a5d8e7" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8a5d8e7');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Mar 17 16:52:17 2009</strong>

Configure script broken on openbsd due to cygwin weirdness
    </pre>
  </div>
</div>
