<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/20d080c" target="_blank">20d080c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-20d080c');">
    prepare for 1.83
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-20d080c');">
    // Claes Wikstrom
  </div>
  <div id="msg-20d080c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-20d080c');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 15:48:24 2009</strong>

prepare for 1.83
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/49fc86f" target="_blank">49fc86f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-49fc86f');">
    docs and also don't fail if authmod:get_headers() don't exist
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-49fc86f');">
    // Claes Wikstrom
  </div>
  <div id="msg-49fc86f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-49fc86f');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 15:32:17 2009</strong>

docs and also don't fail if authmod:get_headers() don't exist
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9ab391e" target="_blank">9ab391e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9ab391e');">
    warn when crypto app is not there
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9ab391e');">
    // Claes Wikstrom
  </div>
  <div id="msg-9ab391e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9ab391e');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 15:00:38 2009</strong>

warn when crypto app is not there
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/abe2833" target="_blank">abe2833</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-abe2833');">
    minor docs for new stats feature
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-abe2833');">
    // Claes Wikstrom
  </div>
  <div id="msg-abe2833" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-abe2833');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 12:31:50 2009</strong>

minor docs for new stats feature
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/da53d3a" target="_blank">da53d3a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-da53d3a');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-da53d3a');">
    // Claes Wikstrom
  </div>
  <div id="msg-da53d3a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-da53d3a');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 12:20:31 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f8d014c" target="_blank">f8d014c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f8d014c');">
    Merge branch 'stats' of git://github.com/oliv3/yaws into stats
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f8d014c');">
    // Claes Wikstrom
  </div>
  <div id="msg-f8d014c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f8d014c');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 3 12:08:18 2009</strong>

Merge branch 'stats' of git://github.com/oliv3/yaws into stats
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3b56900" target="_blank">3b56900</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3b56900');">
    rm t3
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3b56900');">
    // Claes Wikstrom
  </div>
  <div id="msg-3b56900" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3b56900');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Jul 1 22:26:14 2009</strong>

rm t3
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/25028a8" target="_blank">25028a8</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-25028a8');">
    cleanup
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-25028a8');">
    // Claes Wikstrom
  </div>
  <div id="msg-25028a8" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-25028a8');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Jul 1 22:19:06 2009</strong>

cleanup
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5d41acd" target="_blank">5d41acd</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5d41acd');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5d41acd');">
    // Claes Wikstrom
  </div>
  <div id="msg-5d41acd" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5d41acd');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Jul 1 12:22:05 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c73cff6" target="_blank">c73cff6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c73cff6');">
    yaws [PATCH] Use $CC instead of gcc
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c73cff6');">
    // dnz@bk.ru
  </div>
  <div id="msg-c73cff6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c73cff6');">
    <pre>
<strong>Author: dnz@bk.ru &lt;dnz@bk.ru&gt;</strong>
<strong>Date:   Tue Jun 30 15:07:19 2009</strong>

yaws [PATCH] Use $CC instead of gcc

Hi,

I'm just a newbie, but these fixes seemed obvious.
Hope it's useful.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2747a01" target="_blank">2747a01</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2747a01');">
    doc cleanup
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2747a01');">
    // Claes Wikstrom
  </div>
  <div id="msg-2747a01" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2747a01');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jun 30 16:21:17 2009</strong>

doc cleanup
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f7d5ad8" target="_blank">f7d5ad8</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f7d5ad8');">
    configure patch by dnz
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f7d5ad8');">
    // Claes Wikstrom
  </div>
  <div id="msg-f7d5ad8" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f7d5ad8');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jun 30 16:20:37 2009</strong>

configure patch by dnz
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4010fc7" target="_blank">4010fc7</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4010fc7');">
    don't fail if read perms are not ther when followin the .yaws_auth dir down
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4010fc7');">
    // Claes Wikstrom
  </div>
  <div id="msg-4010fc7" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4010fc7');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jun 26 02:34:10 2009</strong>

don't fail if read perms are not ther when followin the .yaws_auth dir down
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5689b6c" target="_blank">5689b6c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5689b6c');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5689b6c');">
    // Claes Wikstrom
  </div>
  <div id="msg-5689b6c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5689b6c');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jun 23 11:24:34 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5c3c546" target="_blank">5c3c546</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5c3c546');">
    Yaws patch
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5c3c546');">
    // Fabian Alenius
  </div>
  <div id="msg-5c3c546" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5c3c546');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian.alenius@gmail.com&gt;</strong>
<strong>Date:   Fri Jun 19 01:25:10 2009</strong>

Yaws patch

Hi!

Here is the patch, as promised. Not sure this solution is optimal but it
should work.

To be honest I've only done basic testing (bit tired by now..) so would
be good if you could give it a run before you put it out. I checked out
the 1.82 tag from github so that's the version you should apply the
patch to.

// Fabian

From 4636b0d096a061a0af6c2034446926bdba4259ed Mon Sep 17 00:00:00 2001
From: Fabian Alenius &lt;faal@faal.(none)&gt;
Date: Fri, 19 Jun 2009 01:17:44 +0200
Subject: [PATCH] Fixed backwards compatibility
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/12c9f01" target="_blank">12c9f01</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-12c9f01');">
    eliminate io_lib:format overhead in yaws_log:fmtnow
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-12c9f01');">
    // Steve Vinoski
  </div>
  <div id="msg-12c9f01" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-12c9f01');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Jun 18 16:49:39 2009</strong>

eliminate io_lib:format overhead in yaws_log:fmtnow
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/edfca30" target="_blank">edfca30</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-edfca30');">
    Comment
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-edfca30');">
    // Olivier Girondel
  </div>
  <div id="msg-edfca30" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-edfca30');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Tue Jun 16 16:38:14 2009</strong>

Comment
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/350765b" target="_blank">350765b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-350765b');">
    Start/stop stats servers
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-350765b');">
    // Olivier Girondel
  </div>
  <div id="msg-350765b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-350765b');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Tue Jun 16 16:31:54 2009</strong>

Start/stop stats servers
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5ceb0cf" target="_blank">5ceb0cf</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5ceb0cf');">
    Start or stop servers when configuration has chenged
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5ceb0cf');">
    // Olivier Girondel
  </div>
  <div id="msg-5ceb0cf" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5ceb0cf');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Tue Jun 16 15:48:11 2009</strong>

Start or stop servers when configuration has chenged
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4d4fad6" target="_blank">4d4fad6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4d4fad6');">
    handle authdirs search properly when docroot not defined (Olivier Girondel)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4d4fad6');">
    // Steve Vinoski
  </div>
  <div id="msg-4d4fad6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4d4fad6');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jun 12 20:54:25 2009</strong>

handle authdirs search properly when docroot not defined (Olivier Girondel)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9459316" target="_blank">9459316</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9459316');">
    Simplify
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9459316');">
    // Olivier Girondel
  </div>
  <div id="msg-9459316" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9459316');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 17:41:52 2009</strong>

Simplify
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9317a44" target="_blank">9317a44</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9317a44');">
    Compile yaws_stats
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9317a44');">
    // Olivier Girondel
  </div>
  <div id="msg-9317a44" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9317a44');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 17:41:13 2009</strong>

Compile yaws_stats
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a0a5329" target="_blank">a0a5329</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a0a5329');">
    Bugfix revproxy
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a0a5329');">
    // Olivier Girondel
  </div>
  <div id="msg-a0a5329" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a0a5329');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 17:27:01 2009</strong>

Bugfix revproxy
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/08e2531" target="_blank">08e2531</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-08e2531');">
    Bugfix revproxy
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-08e2531');">
    // Olivier Girondel
  </div>
  <div id="msg-08e2531" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-08e2531');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 17:25:15 2009</strong>

Bugfix revproxy
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/eedaca5" target="_blank">eedaca5</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-eedaca5');">
    yaws_ctl --stats added
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-eedaca5');">
    // Olivier Girondel
  </div>
  <div id="msg-eedaca5" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-eedaca5');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 16:39:34 2009</strong>

yaws_ctl --stats added
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2a369b3" target="_blank">2a369b3</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2a369b3');">
    README.munin
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2a369b3');">
    // Olivier Girondel
  </div>
  <div id="msg-2a369b3" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2a369b3');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 16:28:05 2009</strong>

README.munin
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9f4cc66" target="_blank">9f4cc66</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9f4cc66');">
    munin scripts
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9f4cc66');">
    // Olivier Girondel
  </div>
  <div id="msg-9f4cc66" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9f4cc66');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 16:24:40 2009</strong>

munin scripts
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a42cf46" target="_blank">a42cf46</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a42cf46');">
    yaws_ctl and conf template
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a42cf46');">
    // Olivier Girondel
  </div>
  <div id="msg-a42cf46" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a42cf46');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 16:24:18 2009</strong>

yaws_ctl and conf template
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/dbaab8b" target="_blank">dbaab8b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-dbaab8b');">
    Stats command
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-dbaab8b');">
    // Olivier Girondel
  </div>
  <div id="msg-dbaab8b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-dbaab8b');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 14:59:06 2009</strong>

Stats command
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4300392" target="_blank">4300392</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4300392');">
    Start stats servers, bytes sent accounting
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4300392');">
    // Olivier Girondel
  </div>
  <div id="msg-4300392" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4300392');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 14:53:54 2009</strong>

Start stats servers, bytes sent accounting
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3f0752a" target="_blank">3f0752a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3f0752a');">
    Sent bytes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3f0752a');">
    // Olivier Girondel
  </div>
  <div id="msg-3f0752a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3f0752a');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Fri Jun 12 14:33:09 2009</strong>

Sent bytes
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4aea292" target="_blank">4aea292</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4aea292');">
    Statistics module added
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4aea292');">
    // Olivier Girondel
  </div>
  <div id="msg-4aea292" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4aea292');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Wed Jun 10 17:12:04 2009</strong>

Statistics module added
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8c969fe" target="_blank">8c969fe</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8c969fe');">
    Support for the statistics option per virtual host
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8c969fe');">
    // Olivier Girondel
  </div>
  <div id="msg-8c969fe" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8c969fe');">
    <pre>
<strong>Author: Olivier Girondel &lt;olivier@biniou.info&gt;</strong>
<strong>Date:   Wed Jun 10 13:28:10 2009</strong>

Support for the statistics option per virtual host
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/311bc70" target="_blank">311bc70</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-311bc70');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-311bc70');">
    // Steve Vinoski
  </div>
  <div id="msg-311bc70" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-311bc70');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Jun 9 23:54:35 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/bd62a8c" target="_blank">bd62a8c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-bd62a8c');">
    Merge branch 'master' of git://github.com/faal/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-bd62a8c');">
    // Claes Wikstrom
  </div>
  <div id="msg-bd62a8c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-bd62a8c');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jun 9 22:49:33 2009</strong>

Merge branch 'master' of git://github.com/faal/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c6a12eb" target="_blank">c6a12eb</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c6a12eb');">
    removed ancient backwards compat flag
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c6a12eb');">
    // Claes Wikstrom
  </div>
  <div id="msg-c6a12eb" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c6a12eb');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jun 9 22:42:58 2009</strong>

removed ancient backwards compat flag
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/856fb79" target="_blank">856fb79</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-856fb79');">
    Removed debug print.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-856fb79');">
    // Fabian Alenius
  </div>
  <div id="msg-856fb79" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-856fb79');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Tue Jun 9 15:17:00 2009</strong>

Removed debug print.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/7d205b5" target="_blank">7d205b5</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-7d205b5');">
    Changed so that auth is setup in yaws_api:setconf/2 instead of yaws:start_embedded/4.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-7d205b5');">
    // Fabian Alenius
  </div>
  <div id="msg-7d205b5" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-7d205b5');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Tue Jun 9 14:15:56 2009</strong>

Changed so that auth is setup in yaws_api:setconf/2 instead of yaws:start_embedded/4.

Previously auth would not be setup when starting in embedded mode using yaws_api:setconf/2
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/7a2fa8d" target="_blank">7a2fa8d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-7a2fa8d');">
    Changed so that Pam and Authmod modules are supplied as atoms instead of lists in .yaws_auth files.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-7a2fa8d');">
    // Fabian Alenius
  </div>
  <div id="msg-7a2fa8d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-7a2fa8d');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Tue Jun 9 10:57:10 2009</strong>

Changed so that Pam and Authmod modules are supplied as atoms instead of lists in .yaws_auth files.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b74df54" target="_blank">b74df54</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b74df54');">
    fixes for traffic tracing in reverse proxy mode (Olivier Girondel)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b74df54');">
    // Steve Vinoski
  </div>
  <div id="msg-b74df54" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b74df54');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Jun 9 09:36:11 2009</strong>

fixes for traffic tracing in reverse proxy mode (Olivier Girondel)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d84e9d2" target="_blank">d84e9d2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d84e9d2');">
    Small fix to remove_multiple_slash/2 to make it remove arbitrarily many slashes.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d84e9d2');">
    // Fabian Alenius
  </div>
  <div id="msg-d84e9d2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d84e9d2');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Tue Jun 9 09:20:44 2009</strong>

Small fix to remove_multiple_slash/2 to make it remove arbitrarily many slashes.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/4c7aaf7" target="_blank">4c7aaf7</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-4c7aaf7');">
    Added a .gitignore to file to ignore generated files, this makes 'git status' a lot more readable.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-4c7aaf7');">
    // Fabian Alenius
  </div>
  <div id="msg-4c7aaf7" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-4c7aaf7');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Tue Jun 9 09:15:52 2009</strong>

Added a .gitignore to file to ignore generated files, this makes 'git status' a lot more readable.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f4d5bdf" target="_blank">f4d5bdf</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f4d5bdf');">
    Merge branch 'master' of git://github.com/klacke/yaws into fix
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f4d5bdf');">
    // Fabian Alenius
  </div>
  <div id="msg-f4d5bdf" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f4d5bdf');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Tue Jun 9 08:47:18 2009</strong>

Merge branch 'master' of git://github.com/klacke/yaws into fix
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/385ae07" target="_blank">385ae07</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-385ae07');">
    Better error msg if erl is not found for win32 users
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-385ae07');">
    // Claes Wikstrom
  </div>
  <div id="msg-385ae07" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-385ae07');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jun 1 13:44:47 2009</strong>

Better error msg if erl is not found for win32 users
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/37ac5f5" target="_blank">37ac5f5</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-37ac5f5');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-37ac5f5');">
    // Claes Wikstrom
  </div>
  <div id="msg-37ac5f5" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-37ac5f5');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jun 1 12:53:13 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c60f1e6" target="_blank">c60f1e6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c60f1e6');">
    Merge git://github.com/klacke/yaws into auth
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c60f1e6');">
    // Fabian Alenius
  </div>
  <div id="msg-c60f1e6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c60f1e6');">
    <pre>
<strong>Author: Fabian Alenius &lt;faal@faal.(none)&gt;</strong>
<strong>Date:   Sun May 31 02:45:00 2009</strong>

Merge git://github.com/klacke/yaws into auth
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d781406" target="_blank">d781406</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d781406');">
    indent
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d781406');">
    // Claes Wikstrom
  </div>
  <div id="msg-d781406" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d781406');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri May 29 23:50:27 2009</strong>

indent
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8f7fae1" target="_blank">8f7fae1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8f7fae1');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8f7fae1');">
    // Claes Wikstrom
  </div>
  <div id="msg-8f7fae1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8f7fae1');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri May 29 10:55:02 2009</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3aabdb4" target="_blank">3aabdb4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3aabdb4');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3aabdb4');">
    // Claes Wikstrom
  </div>
  <div id="msg-3aabdb4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3aabdb4');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 23:31:45 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/45ae3b4" target="_blank">45ae3b4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-45ae3b4');">
    prepare for 1.82
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-45ae3b4');">
    // Claes Wikstrom
  </div>
  <div id="msg-45ae3b4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-45ae3b4');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu May 28 23:08:22 2009</strong>

prepare for 1.82
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a679f38" target="_blank">a679f38</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a679f38');">
    --load and --id togehtehr didn't work
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a679f38');">
    // Claes Wikstrom
  </div>
  <div id="msg-a679f38" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a679f38');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed May 20 17:13:20 2009</strong>

--load and --id togehtehr didn't work
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/dc206fd" target="_blank">dc206fd</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-dc206fd');">
    Moved the parsing of .yaws_auth files to a seperate function
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-dc206fd');">
    // Fabian Alenius
  </div>
  <div id="msg-dc206fd" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-dc206fd');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Mon May 11 19:24:57 2009</strong>

Moved the parsing of .yaws_auth files to a seperate function
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e038ed1" target="_blank">e038ed1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e038ed1');">
    Cleaning up yaws_config.erl, removing add_yaws_auth(...) since it is no longer neccessary. Also removed some debug prints
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e038ed1');">
    // Fabian Alenius
  </div>
  <div id="msg-e038ed1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e038ed1');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Mon May 11 17:00:31 2009</strong>

Cleaning up yaws_config.erl, removing add_yaws_auth(...) since it is no longer neccessary. Also removed some debug prints
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d83c20c" target="_blank">d83c20c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d83c20c');">
    Merge git://github.com/klacke/yaws into auth
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d83c20c');">
    // Fabian Alenius
  </div>
  <div id="msg-d83c20c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d83c20c');">
    <pre>
<strong>Author: Fabian Alenius &lt;fabian@havsbrax.(none)&gt;</strong>
<strong>Date:   Mon May 11 16:26:21 2009</strong>

Merge git://github.com/klacke/yaws into auth
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/dcce587" target="_blank">dcce587</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-dcce587');">
    Merge branch 'auth' of git@github.com:faal/yaws into branch-name
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-dcce587');">
    // Fabian Alenius
  </div>
  <div id="msg-dcce587" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-dcce587');">
    <pre>
<strong>Author: Fabian Alenius &lt;faal@faal.(none)&gt;</strong>
<strong>Date:   Wed May 6 00:40:21 2009</strong>

Merge branch 'auth' of git@github.com:faal/yaws into branch-name
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/37e5aa4" target="_blank">37e5aa4</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-37e5aa4');">
    1. Changed so that yaws searches recursively for .yaws_auth files in the docroot. 2. Directories containing .yaws_auth files no longer has to be specified in the config file to be searched. 3. Code still contains some debug code which needs to be removed.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-37e5aa4');">
    // Fabian Alenius
  </div>
  <div id="msg-37e5aa4" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-37e5aa4');">
    <pre>
<strong>Author: Fabian Alenius &lt;faal@faal.(none)&gt;</strong>
<strong>Date:   Wed May 6 00:39:46 2009</strong>

1. Changed so that yaws searches recursively for .yaws_auth files in the docroot. 2. Directories containing .yaws_auth files no longer has to be specified in the config file to be searched. 3. Code still contains some debug code which needs to be removed.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c4d4f83" target="_blank">c4d4f83</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c4d4f83');">
    Merge branch 'auth' of git@github.com:faal/yaws into old
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c4d4f83');">
    // Fabian Alenius
  </div>
  <div id="msg-c4d4f83" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c4d4f83');">
    <pre>
<strong>Author: Fabian Alenius &lt;faal@faal.(none)&gt;</strong>
<strong>Date:   Sun May 3 18:59:05 2009</strong>

Merge branch 'auth' of git@github.com:faal/yaws into old
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2cf5076" target="_blank">2cf5076</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2cf5076');">
    Sorted the examples in the menu in alphabetic order to make it easier to find what you're looking for.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2cf5076');">
    // Fabian Alenius
  </div>
  <div id="msg-2cf5076" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2cf5076');">
    <pre>
<strong>Author: Fabian Alenius &lt;faal@faal.(none)&gt;</strong>
<strong>Date:   Sun May 3 18:54:18 2009</strong>

Sorted the examples in the menu in alphabetic order to make it easier to find what you're looking for.
    </pre>
  </div>
</div>
