<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f1988a2" target="_blank">f1988a2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f1988a2');">
    release work
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f1988a2');">
    // Claes Wikstrom
  </div>
  <div id="msg-f1988a2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f1988a2');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Feb 9 23:07:42 2010</strong>

release work
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1e1850f" target="_blank">1e1850f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1e1850f');">
    release work
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1e1850f');">
    // Claes Wikstrom
  </div>
  <div id="msg-1e1850f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1e1850f');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Feb 9 23:02:33 2010</strong>

release work
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/855d191" target="_blank">855d191</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-855d191');">
    apparently erl can ?? soon be an executable, canot grep in script
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-855d191');">
    // Claes Wikstrom
  </div>
  <div id="msg-855d191" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-855d191');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@zoe.(none)&gt;</strong>
<strong>Date:   Tue Feb 9 12:37:52 2010</strong>

apparently erl can ?? soon be an executable, canot grep in script
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/28f44b0" target="_blank">28f44b0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-28f44b0');">
    allow caller to set Host header for SOAP requests
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-28f44b0');">
    // Steve Vinoski
  </div>
  <div id="msg-28f44b0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-28f44b0');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Feb 6 22:19:30 2010</strong>

allow caller to set Host header for SOAP requests
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d4fec79" target="_blank">d4fec79</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d4fec79');">
    added support for OTP new ssl implementation
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d4fec79');">
    // Claes Wikstrom
  </div>
  <div id="msg-d4fec79" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d4fec79');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Feb 1 09:12:51 2010</strong>

added support for OTP new ssl implementation
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/bd0bf89" target="_blank">bd0bf89</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-bd0bf89');">
    no utf8 in the author name
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-bd0bf89');">
    // Claes Wikstrom
  </div>
  <div id="msg-bd0bf89" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-bd0bf89');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jan 12 15:33:23 2010</strong>

no utf8 in the author name
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/7680b32" target="_blank">7680b32</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-7680b32');">
    re-prepare for 1.87
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-7680b32');">
    // Claes Wikstrom
  </div>
  <div id="msg-7680b32" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-7680b32');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jan 11 22:11:26 2010</strong>

re-prepare for 1.87
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a59acad" target="_blank">a59acad</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a59acad');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a59acad');">
    // Claes Wikstrom
  </div>
  <div id="msg-a59acad" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a59acad');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jan 11 22:08:06 2010</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/35ff951" target="_blank">35ff951</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-35ff951');">
    patch by Andrei Soroker to strip the port part in #redir_self records - this patch may break some code, users that use redir_self() and unconditionally strip off their optional port number are affected
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-35ff951');">
    // Claes Wikstrom
  </div>
  <div id="msg-35ff951" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-35ff951');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jan 11 22:07:53 2010</strong>

patch by Andrei Soroker to strip the port part in #redir_self records - this patch may break some code, users that use redir_self() and unconditionally strip off their optional port number are affected
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3e74906" target="_blank">3e74906</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3e74906');">
    support some extra status codes in code_to_phrase
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3e74906');">
    // Steve Vinoski
  </div>
  <div id="msg-3e74906" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3e74906');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jan 8 06:30:41 2010</strong>

support some extra status codes in code_to_phrase
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/cda8035" target="_blank">cda8035</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-cda8035');">
    Merge branch 'master' of git@github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-cda8035');">
    // Claes Wikstrom
  </div>
  <div id="msg-cda8035" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-cda8035');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Jan 7 12:33:45 2010</strong>

Merge branch 'master' of git@github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/30a39ae" target="_blank">30a39ae</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-30a39ae');">
    drop spaces before parsing ints - patch by Colm Dougan
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-30a39ae');">
    // Claes Wikstrom
  </div>
  <div id="msg-30a39ae" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-30a39ae');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Thu Jan 7 11:04:46 2010</strong>

drop spaces before parsing ints - patch by Colm Dougan
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/297f2c9" target="_blank">297f2c9</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-297f2c9');">
    fix setting of ERTS_MAJOR and ERTS_MINOR
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-297f2c9');">
    // Steve Vinoski
  </div>
  <div id="msg-297f2c9" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-297f2c9');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Jan 6 06:32:59 2010</strong>

fix setting of ERTS_MAJOR and ERTS_MINOR
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f5eb9d5" target="_blank">f5eb9d5</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f5eb9d5');">
    conditional compile of websockets
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f5eb9d5');">
    // Claes Wikstrom
  </div>
  <div id="msg-f5eb9d5" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f5eb9d5');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jan 5 22:51:56 2010</strong>

conditional compile of websockets
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9d929ca" target="_blank">9d929ca</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9d929ca');">
    prepare for 1.87
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9d929ca');">
    // Claes Wikstrom
  </div>
  <div id="msg-9d929ca" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9d929ca');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Tue Jan 5 14:46:02 2010</strong>

prepare for 1.87
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8176fe9" target="_blank">8176fe9</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8176fe9');">
    reintroduced yaws_vdir.erl, erroneoulsy removed
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8176fe9');">
    // Claes Wikstrom
  </div>
  <div id="msg-8176fe9" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8176fe9');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Dec 21 17:37:29 2009</strong>

reintroduced yaws_vdir.erl, erroneoulsy removed
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9e12baf" target="_blank">9e12baf</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9e12baf');">
    proper handling of "/" appmod with excluded paths (patch from wde)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9e12baf');">
    // Steve Vinoski
  </div>
  <div id="msg-9e12baf" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9e12baf');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Dec 20 18:28:08 2009</strong>

proper handling of "/" appmod with excluded paths (patch from wde)

Added new unit tests for appmods, with both / and non-/ tests. The /
tests include exclude_paths testing.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/afa6a19" target="_blank">afa6a19</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-afa6a19');">
    ensure yaws ebin is in the path for multipart tests
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-afa6a19');">
    // Steve Vinoski
  </div>
  <div id="msg-afa6a19" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-afa6a19');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Dec 20 16:02:05 2009</strong>

ensure yaws ebin is in the path for multipart tests
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/790ce8a" target="_blank">790ce8a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-790ce8a');">
    minor indentation and comment cleanup
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-790ce8a');">
    // Steve Vinoski
  </div>
  <div id="msg-790ce8a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-790ce8a');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Dec 19 06:53:44 2009</strong>

minor indentation and comment cleanup
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/762a73d" target="_blank">762a73d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-762a73d');">
    Merge branch 'master' of git://github.com/davide/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-762a73d');">
    // Claes Wikstrom
  </div>
  <div id="msg-762a73d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-762a73d');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Dec 18 23:58:02 2009</strong>

Merge branch 'master' of git://github.com/davide/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9855e31" target="_blank">9855e31</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9855e31');">
    patch from wde solving a problem with appmod exclude paths and verify_upgrade
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9855e31');">
    // Claes Wikstrom
  </div>
  <div id="msg-9855e31" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9855e31');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Dec 18 23:55:21 2009</strong>

patch from wde solving a problem with appmod exclude paths and verify_upgrade
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8c2e90d" target="_blank">8c2e90d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8c2e90d');">
    yaws_server: fixed the test for whether to close the socket. The yaws:outh_get_doclose() doesn't return a boolean and it requires the outh dicionary entry to be set (sometimes it isn't).
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8c2e90d');">
    // davide
  </div>
  <div id="msg-8c2e90d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8c2e90d');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Fri Dec 18 23:02:32 2009</strong>

yaws_server: fixed the test for whether to close the socket.
The yaws:outh_get_doclose() doesn't return a boolean and it requires the outh dicionary entry to be set (sometimes it isn't).
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/785b7c6" target="_blank">785b7c6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-785b7c6');">
    Added documentation for the HTML5 Web Sockets implementation.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-785b7c6');">
    // davide
  </div>
  <div id="msg-785b7c6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-785b7c6');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Fri Dec 18 19:27:00 2009</strong>

Added documentation for the HTML5 Web Sockets implementation.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/da8ebc6" target="_blank">da8ebc6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-da8ebc6');">
    Get the websocket return value to enforce #outh{doclose=false} using the {connection, erase} header.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-da8ebc6');">
    // davide
  </div>
  <div id="msg-da8ebc6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-da8ebc6');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Fri Dec 18 17:58:15 2009</strong>

Get the websocket return value to enforce #outh{doclose=false} using the {connection, erase} header.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/7fdc54a" target="_blank">7fdc54a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-7fdc54a');">
    HTML5 Web Sockets support.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-7fdc54a');">
    // davide
  </div>
  <div id="msg-7fdc54a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-7fdc54a');">
    <pre>
<strong>Author: davide &lt;nesrait@gmail.com&gt;</strong>
<strong>Date:   Fri Dec 18 16:44:25 2009</strong>

HTML5 Web Sockets support.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d63642e" target="_blank">d63642e</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d63642e');">
    do not pass the --id option if the default id is used
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d63642e');">
    // Steve Vinoski
  </div>
  <div id="msg-d63642e" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d63642e');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Dec 15 04:26:32 2009</strong>

do not pass the --id option if the default id is used

The default id in the code is represented as the string "default". If
the --id option passes default to set the id, it becomes the atom
default which of course differs from the string "default". By not
using --id to specify the default id, we get the value "default" as
the default.

Make sure ids passed in via the --id option that yaws_sup.erl sees as
atoms are converted to lists. This matches what's done for other
options involving ids such as --check and --stop.

Other changes in this commit make sure that the $HOME/.yaws/yaws/ID
path is used consistently across the code and documentation, and also
a couple minor whitespace/indentation cleanups.
    </pre>
  </div>
</div>
