<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/589b535" target="_blank">589b535</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-589b535');">
    prepare for 1.95
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-589b535');">
    // Claes Wikstrom
  </div>
  <div id="msg-589b535" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-589b535');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Oct 17 20:14:43 2012</strong>

prepare for 1.95
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/0da0628" target="_blank">0da0628</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-0da0628');">
    The --heart option didn't work as expected when yaws ran out of filedescriptors - capflam
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-0da0628');">
    // Claes Wikstrom
  </div>
  <div id="msg-0da0628" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-0da0628');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Oct 17 19:56:35 2012</strong>

The --heart option didn't work as expected when yaws ran out of filedescriptors - capflam
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b731873" target="_blank">b731873</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b731873');">
    Merge branch 'master' of github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b731873');">
    // Claes Wikstrom
  </div>
  <div id="msg-b731873" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b731873');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Oct 17 19:54:10 2012</strong>

Merge branch 'master' of github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3c36e2a" target="_blank">3c36e2a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3c36e2a');">
    more WebDAV fixes (lyk0rian)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3c36e2a');">
    // Steve Vinoski
  </div>
  <div id="msg-3c36e2a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3c36e2a');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Oct 17 15:32:41 2012</strong>

more WebDAV fixes (lyk0rian)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/128b002" target="_blank">128b002</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-128b002');">
    Merge branch 'master' of github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-128b002');">
    // Claes Wikstrom
  </div>
  <div id="msg-128b002" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-128b002');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Oct 15 20:12:55 2012</strong>

Merge branch 'master' of github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e3c1631" target="_blank">e3c1631</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e3c1631');">
    news
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e3c1631');">
    // Claes Wikstrom
  </div>
  <div id="msg-e3c1631" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e3c1631');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Oct 15 20:12:47 2012</strong>

news
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/039c300" target="_blank">039c300</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-039c300');">
    add missing make rule for davconf
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-039c300');">
    // Steve Vinoski
  </div>
  <div id="msg-039c300" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-039c300');">
    <pre>
<strong>Author: Steve Vinoski &lt;steve@basho.com&gt;</strong>
<strong>Date:   Sun Oct 14 21:31:58 2012</strong>

add missing make rule for davconf
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/efa9eff" target="_blank">efa9eff</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-efa9eff');">
    WebDAV compliancy rework (Tjeerd van der Laan)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-efa9eff');">
    // Steve Vinoski
  </div>
  <div id="msg-efa9eff" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-efa9eff');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Jul 12 03:25:03 2012</strong>

WebDAV compliancy rework (Tjeerd van der Laan)

The WebDAV support is reworked and adds class 1, 2 and 3 compliancy
which includes:

* XML request body parsing and  multistatus responses

* PROPFIND and PROPPATCH methods returning properties asked for

* all RFC4918 properties, the Apache executable property plus some
  Microsoft extensions

* locking mechanism (class 2 compliancy) on all destructive methods

* If header parsing
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/00aa12d" target="_blank">00aa12d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-00aa12d');">
    Follow structure of EHTML as stated in manual
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-00aa12d');">
    // tjeerd
  </div>
  <div id="msg-00aa12d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-00aa12d');">
    <pre>
<strong>Author: tjeerd &lt;tjeerd@yolt.nl&gt;</strong>
<strong>Date:   Sun Aug 26 13:54:09 2012</strong>

Follow structure of EHTML as stated in manual
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/e662e51" target="_blank">e662e51</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-e662e51');">
    Added sorting of subconfigdir
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-e662e51');">
    // tjeerd
  </div>
  <div id="msg-e662e51" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-e662e51');">
    <pre>
<strong>Author: tjeerd &lt;tjeerd@yolt.nl&gt;</strong>
<strong>Date:   Sun Aug 26 13:49:28 2012</strong>

Added sorting of subconfigdir
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/75dbb60" target="_blank">75dbb60</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-75dbb60');">
    add a configurable dispatch module
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-75dbb60');">
    // Steve Vinoski
  </div>
  <div id="msg-75dbb60" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-75dbb60');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Sep 26 00:06:02 2012</strong>

add a configurable dispatch module

Allow an application to supply its own dispatch module for a server by
setting the new dispatchmod variable in the server config. The module is
expected to export a dispatch/1 function that returns one of the following
atoms:

* done: this indicates the dispatch module has handled the request and sent
  the response, and Yaws should go look for a new request on this
  connection

* closed: same as "done" but also indicates the dispatch module has closed
  the connection

* continue: this tells Yaws to continue with the normal dispatch path
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1615f7d" target="_blank">1615f7d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1615f7d');">
    Merge pull request #127 from saleyn/set_cookie
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1615f7d');">
    // Claes Wikstrom
  </div>
  <div id="msg-1615f7d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1615f7d');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Oct 7 19:36:01 2012</strong>

Merge pull request #127 from saleyn/set_cookie

Added RFC6265 compliant variant of yaws_api:set_cookie/3.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5b7c019" target="_blank">5b7c019</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5b7c019');">
    Added more test cases.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5b7c019');">
    // serge
  </div>
  <div id="msg-5b7c019" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5b7c019');">
    <pre>
<strong>Author: serge &lt;saleyn@gmail.com&gt;</strong>
<strong>Date:   Sat Oct 6 18:00:05 2012</strong>

Added more test cases.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6abc02a" target="_blank">6abc02a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6abc02a');">
    Added test cases.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6abc02a');">
    // serge
  </div>
  <div id="msg-6abc02a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6abc02a');">
    <pre>
<strong>Author: serge &lt;saleyn@gmail.com&gt;</strong>
<strong>Date:   Sat Oct 6 17:51:32 2012</strong>

Added test cases.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/00c152b" target="_blank">00c152b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-00c152b');">
    Added RFC6265 compliant variant of setcookie.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-00c152b');">
    // serge
  </div>
  <div id="msg-00c152b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-00c152b');">
    <pre>
<strong>Author: serge &lt;saleyn@gmail.com&gt;</strong>
<strong>Date:   Sat Oct 6 16:24:14 2012</strong>

Added RFC6265 compliant variant of setcookie.

The new set_cookie/3 function implements more complete RFC2109
cookie formatting than setcookie/6 and is 10x - 15x more efficient
than its old setcookie counterpart because of avoiding the use of
io_lib:format/2.  The setcookie/2 through setcookie/6 are marked
as deprecated.  The function is named set_cookie rather than setcookie
to facilitate the ease of depricating the old implementation.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1e7a122" target="_blank">1e7a122</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1e7a122');">
    some man page cleanup/repair
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1e7a122');">
    // Steve Vinoski
  </div>
  <div id="msg-1e7a122" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1e7a122');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Oct 4 20:28:58 2012</strong>

some man page cleanup/repair
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f6ba7ca" target="_blank">f6ba7ca</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f6ba7ca');">
    document 127.0.0.1 as the default listen interface
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f6ba7ca');">
    // Steve Vinoski
  </div>
  <div id="msg-f6ba7ca" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f6ba7ca');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Oct 4 18:26:56 2012</strong>

document 127.0.0.1 as the default listen interface

Fix the yaws.conf man page to state that 127.0.0.1 is the default listen
interface for a virtual server. Also document the same in the yaws.tex
file.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ba34c61" target="_blank">ba34c61</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ba34c61');">
    Fix SSL socket wrapping
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ba34c61');">
    // Christopher Faulet
  </div>
  <div id="msg-ba34c61" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ba34c61');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Tue Oct 2 12:14:39 2012</strong>

Fix SSL socket wrapping

We must be careful when we rely on Arg#arg.clisock in Yaws modules
because the socket is wrapped in case of SSL connections.

Thanks to Jean-Charles Campagne.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/faef983" target="_blank">faef983</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-faef983');">
    add some missing HTTP status codes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-faef983');">
    // Steve Vinoski
  </div>
  <div id="msg-faef983" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-faef983');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Oct 1 09:34:44 2012</strong>

add some missing HTTP status codes
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/77142a0" target="_blank">77142a0</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-77142a0');">
    update known dialyzer warnings file
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-77142a0');">
    // Christopher Faulet
  </div>
  <div id="msg-77142a0" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-77142a0');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Tue Sep 18 10:11:46 2012</strong>

update known dialyzer warnings file
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a66f8a3" target="_blank">a66f8a3</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a66f8a3');">
    Parse extensions and trailing headers of chunked transfer encoded requests
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a66f8a3');">
    // Christopher Faulet
  </div>
  <div id="msg-a66f8a3" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a66f8a3');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Wed Sep 12 17:26:58 2012</strong>

Parse extensions and trailing headers of chunked transfer encoded requests

Chunk extensions and trailing headers are parsed but ignored in requests
and are not supported in responses. It is a strange feature of the RFC-2619
and would be hard to implement. Moreover, this feature is rarely supported
by clients and servers and even less used.
So, without any concrete use-case, no further work will be done on this
subject.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f3a31fe" target="_blank">f3a31fe</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f3a31fe');">
    Fix tests on Transfer-Encoding header to be case-insensitive
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f3a31fe');">
    // Christopher Faulet
  </div>
  <div id="msg-f3a31fe" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f3a31fe');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Wed Sep 12 17:19:59 2012</strong>

Fix tests on Transfer-Encoding header to be case-insensitive
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5101fde" target="_blank">5101fde</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5101fde');">
    Optimize the ACL checks during the request's authentication
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5101fde');">
    // Christopher Faulet
  </div>
  <div id="msg-5101fde" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5101fde');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Thu Jul 26 17:36:30 2012</strong>

Optimize the ACL checks during the request's authentication

Now, in yaws_server:handle_auth/4, the client ip is no more converted into
integer. All ip addresses in #auth.acl are of the type ip_address(). That makes
easier the checking of the client ip.
To clean up the code, functions that parses and checks the allowed/denied ip
addresses with the client ip were moved into yaws.erl.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3784dfb" target="_blank">3784dfb</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3784dfb');">
    Merge branch 'master' of github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3784dfb');">
    // Claes Wikstrom
  </div>
  <div id="msg-3784dfb" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3784dfb');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Sep 10 04:11:59 2012</strong>

Merge branch 'master' of github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8551256" target="_blank">8551256</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8551256');">
    Added support to configure ciphers in ssl, previously the ciphers = Val stricng in yaws.conf required the Val to be a string according the openssl cipher string spec language. Now we specify an erlang list instead, the list shall comply to the output of ssl:cipher_suites()
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8551256');">
    // Claes Wikstrom
  </div>
  <div id="msg-8551256" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8551256');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Sep 10 04:11:47 2012</strong>

Added support to configure ciphers in ssl, previously the ciphers = Val stricng in yaws.conf required the Val to be a string according the openssl cipher string spec language. Now we specify an erlang list instead, the list shall comply to the output of ssl:cipher_suites()
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/7688b46" target="_blank">7688b46</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-7688b46');">
    update known dialyzer warnings file
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-7688b46');">
    // Steve Vinoski
  </div>
  <div id="msg-7688b46" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-7688b46');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Sep 9 22:49:38 2012</strong>

update known dialyzer warnings file
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5f3ea37" target="_blank">5f3ea37</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5f3ea37');">
    Merge pull request #124 from jj1bdx/jj1bdx-dialyzer-fix
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5f3ea37');">
    // Claes Wikstrom
  </div>
  <div id="msg-5f3ea37" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5f3ea37');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sat Sep 8 09:13:28 2012</strong>

Merge pull request #124 from jj1bdx/jj1bdx-dialyzer-fix

Update Makefile and src/Makefile
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9b86f4a" target="_blank">9b86f4a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9b86f4a');">
    Update Makefile and src/Makefile
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9b86f4a');">
    // Kenji Rikitake
  </div>
  <div id="msg-9b86f4a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9b86f4a');">
    <pre>
<strong>Author: Kenji Rikitake &lt;kenji.rikitake@acm.org&gt;</strong>
<strong>Date:   Sat Sep 8 08:55:30 2012</strong>

Update Makefile and src/Makefile

* Targets in `Makefile` of `yaws.plt` and `dialyzer` calls
  dialyzer with two target directories, `ebin` and `src`;
  this causes the error of duplicate modules.
  Checking out the .beam files under `ebin` is sufficient
  for dialyzer; `src` is removed.

* Target `mime_type_c.beam` in `src/Makefile` is
  superfluous and generates a spurious .beam file in
  the `src` directory, so the target is removed.
  Also target `charset.def` in `src/Makefile` should be
  dependent on `../ebin/mime_type_c.beam`, so this is
  also changed from the previous target without the
  directory path.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2ff32fe" target="_blank">2ff32fe</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2ff32fe');">
    update mime.types file
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2ff32fe');">
    // Steve Vinoski
  </div>
  <div id="msg-2ff32fe" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2ff32fe');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Sep 1 20:15:03 2012</strong>

update mime.types file
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d508c6b" target="_blank">d508c6b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d508c6b');">
    add startup script for FreeBSD 9 (Thomas Elsgaard)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d508c6b');">
    // Steve Vinoski
  </div>
  <div id="msg-d508c6b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d508c6b');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sun Aug 26 02:10:34 2012</strong>

add startup script for FreeBSD 9 (Thomas Elsgaard)

Add scripts/freebsd/yaws for FreeBSD version 9 or later. The original
script at scripts/freebsd/yaws.sh is retained for use with FreeBSD versions
prior to 9.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/66f50e6" target="_blank">66f50e6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-66f50e6');">
    make sure "rebar eunit" passes
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-66f50e6');">
    // Steve Vinoski
  </div>
  <div id="msg-66f50e6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-66f50e6');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Aug 24 16:33:06 2012</strong>

make sure "rebar eunit" passes

When using yaws as an app dependency for another application built with
rebar, I noticed that testing that application with "rebar eunit" would
fail while testing yaws. It was easy to work around with "rebar eunit
skip_deps=true" but yaws really should pass its tests when tested via
rebar.

Change rebar.config to add ibrowse as a dependency. It's used only for
testing, but rebar doesn't support test-only dependencies, plus it's
filtered out during release generation anyway.

Modify some of the test files to be able to find ibrowse include files
regardless of whether they're built via make or via rebar. Also rename all
non-eunit test functions ending in "_test" so they don't confuse eunit. Also
had to move the embedded_yaws_id_dir test from eunit to t2 because it fails
under "rebar eunit" when yaws is a dependency for another app. It fails
because it calls into the yaws_api:embedded_start_conf function which tries
to call application:load(yaws), but paths aren't properly set up to allow
that to work under these testing circumstances.

Note that not all tests currently run under rebar; building with make and
then running "make test" results in many more tests being executed. Fixing
this will come later.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d0a90a9" target="_blank">d0a90a9</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d0a90a9');">
    revert commit d990b30
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d0a90a9');">
    // Steve Vinoski
  </div>
  <div id="msg-d0a90a9" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d0a90a9');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Aug 24 15:27:20 2012</strong>

revert commit d990b30

Commit d990b30 was intended to fix issue #122 but my testing was flawed, so
I'm reverting it. The real issue seems to be a bug with reltool not
honoring app overrides of sys-level mod_cond settings.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d990b30" target="_blank">d990b30</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d990b30');">
    make sure more modules are included in a release (issue #122)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d990b30');">
    // Steve Vinoski
  </div>
  <div id="msg-d990b30" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d990b30');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Aug 24 05:21:56 2012</strong>

make sure more modules are included in a release (issue #122)

The problem that caused issue #122 is that the yaws_outmod module, which
isn't directly referenced by any other yaws module, was not being included
in the application release. Change the mod_cond in rel/reltool.config to
all rather than app to ensure yaws_outmod gets included.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/b415950" target="_blank">b415950</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-b415950');">
    document the new yaws_api:reformat_header/2 function
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-b415950');">
    // Steve Vinoski
  </div>
  <div id="msg-b415950" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-b415950');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Aug 23 23:34:49 2012</strong>

document the new yaws_api:reformat_header/2 function
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/602dba7" target="_blank">602dba7</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-602dba7');">
    add flexible variant of yaws_api:reformat_header
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-602dba7');">
    // Steve Vinoski
  </div>
  <div id="msg-602dba7" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-602dba7');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Aug 22 05:14:57 2012</strong>

add flexible variant of yaws_api:reformat_header

Add a new yaws_api:reformat_header/2 that takes a formatting function as
the second argument. The old reformat_header/1 now just calls this, passing
the original formatting function.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a1dbdc6" target="_blank">a1dbdc6</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a1dbdc6');">
    Merge pull request #121 from jbothma/master
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a1dbdc6');">
    // Steve Vinoski
  </div>
  <div id="msg-a1dbdc6" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a1dbdc6');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Aug 7 23:20:13 2012</strong>

Merge pull request #121 from jbothma/master

Add basic websocket test.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/1c4d428" target="_blank">1c4d428</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-1c4d428');">
    support Raspberry Pi in configure.in (Anders Nygren)
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-1c4d428');">
    // Steve Vinoski
  </div>
  <div id="msg-1c4d428" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-1c4d428');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Aug 7 21:52:59 2012</strong>

support Raspberry Pi in configure.in (Anders Nygren)
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/79ba3ba" target="_blank">79ba3ba</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-79ba3ba');">
    fix setting of yawsid_opts variable in OS X startup script
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-79ba3ba');">
    // Steve Vinoski
  </div>
  <div id="msg-79ba3ba" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-79ba3ba');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Aug 6 04:36:23 2012</strong>

fix setting of yawsid_opts variable in OS X startup script
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/940ea3a" target="_blank">940ea3a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-940ea3a');">
    Add basic websocket test.
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-940ea3a');">
    // JD Bothma
  </div>
  <div id="msg-940ea3a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-940ea3a');">
    <pre>
<strong>Author: JD Bothma &lt;jbothma@gmail.com&gt;</strong>
<strong>Date:   Tue Jul 31 00:03:20 2012</strong>

Add basic websocket test.

It performs the handshake, then sends one text message and checks
that it is echoed back correctly.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2f3a4bf" target="_blank">2f3a4bf</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2f3a4bf');">
    Improve how Yaws is started in embedded mode
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2f3a4bf');">
    // Christopher Faulet
  </div>
  <div id="msg-2f3a4bf" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2f3a4bf');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Thu Jul 26 11:16:24 2012</strong>

Improve how Yaws is started in embedded mode

The main change concerns the function yaws:create_sconf/2. Now, this function
relies on yaws_config:make_default_sconf/2 to create a default #sconf record.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/40d7acd" target="_blank">40d7acd</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-40d7acd');">
    Check missing fields in yaws_config:eq_sconfs/2
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-40d7acd');">
    // Christopher Faulet
  </div>
  <div id="msg-40d7acd" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-40d7acd');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Thu Jul 26 09:27:12 2012</strong>

Check missing fields in yaws_config:eq_sconfs/2
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/89a64ef" target="_blank">89a64ef</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-89a64ef');">
    Make the mime types mappings configurable
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-89a64ef');">
    // Christopher Faulet
  </div>
  <div id="msg-89a64ef" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-89a64ef');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Thu Jul 19 15:39:26 2012</strong>

Make the mime types mappings configurable

Now, it possible to customize the global mime types mappings and to overload
it for each virtual server. It can be done using following directives in the
global part or the server part of the configuration:

* default_type: Defines the default mime type to be used where Yaws cannot
  determine it by its mime types mappings (default: text/plain).
  In the server part, this directive overloads the global one.

* default_charset: Defines the default charset to be added when a response
  content-type is text/* (default: none). In the server part, this directive
  overloads the global one.

* mime_types_file: Overrides the default mime.types file included with Yaws
  (default: ${PREFIX}/lib/yaws/priv/mime.types). In the server part, this
  directive overloads the global one but mappings defined in this file will
  not overload those defined by add_types directives in the global part.

* add_types: Specifies one or more mappings between mime types and file
  extensions. More than one extension can be assigned to a mime type. If a
  mapping is defined in the global part and redefined in a server part using
  this directive, then the later is used. Else the global one is kept.

* add_charsets: Specifies one or more mappings between charsets and file
  extensions. More than one extension can be assigned to a charset. If a
  mapping is defined in the global part and redefined in a server part using
  this directive, then the later is used. Else the global one is kept.

Here is an example:

  default_type = text/html

  &lt;server localhost&gt;
      port = 8000
      listen = 0.0.0.0
      docroot = /var/www
      # nothing is overloaded in the vhost
  &lt;/server&gt;

  &lt;server localhost&gt;
      port = 8001
      listen = 0.0.0.0
      docroot = /var/www

      # overload global configuration:
      default_type    = text/plain
      mime_types_file = /etc/mime.types
      add_types       = &lt;text/xhtml, yaws&gt; &lt;application/x-test, tst test&gt;
      default_charset = UTF-8
      add_charsets    = &lt;ISO-8859-1, php html yaws&gt; &lt;US-ASCII, tst&gt;
  &lt;/server&gt;

During Yaws compilation, a default module 'mime_types' is created using the
default mime.types file. Then, when yaws starts up, this module is
re-generated, re-compiled and loaded dynamically. The new module replaces the
default one but the .beam file is unchanged. So if one of these steps failed,
we fall back on the default module.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a5515f2" target="_blank">a5515f2</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a5515f2');">
    Fix return value of yaws_server:is_auth/2 when no auth structure is found
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a5515f2');">
    // Christopher Faulet
  </div>
  <div id="msg-a5515f2" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a5515f2');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Tue Jul 24 18:25:53 2012</strong>

Fix return value of yaws_server:is_auth/2 when no auth structure is found
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ca7f85f" target="_blank">ca7f85f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ca7f85f');">
    Merge pull request #117 from tuncer/noderunner
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ca7f85f');">
    // Steve Vinoski
  </div>
  <div id="msg-ca7f85f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ca7f85f');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Jul 14 03:28:44 2012</strong>

Merge pull request #117 from tuncer/noderunner

Sync rel/files/yaws with upstream template
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ef5e555" target="_blank">ef5e555</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ef5e555');">
    Sync rel/files/yaws with upstream template
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ef5e555');">
    // Tuncer Ayaz
  </div>
  <div id="msg-ef5e555" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ef5e555');">
    <pre>
<strong>Author: Tuncer Ayaz &lt;tuncer.ayaz@gmail.com&gt;</strong>
<strong>Date:   Sat Jul 14 00:46:24 2012</strong>

Sync rel/files/yaws with upstream template
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c99d247" target="_blank">c99d247</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c99d247');">
    Merge pull request #116 from sumup/feature/soap12_imports_namespaces
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c99d247');">
    // Claes Wikstrom
  </div>
  <div id="msg-c99d247" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c99d247');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Fri Jul 13 10:32:06 2012</strong>

Merge pull request #116 from sumup/feature/soap12_imports_namespaces

Feature/soap12 imports namespaces
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2ad166a" target="_blank">2ad166a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2ad166a');">
    server_sent_events: end gen_server process if send fails
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2ad166a');">
    // Steve Vinoski
  </div>
  <div id="msg-2ad166a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2ad166a');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Jul 12 02:31:24 2012</strong>

server_sent_events: end gen_server process if send fails
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6c6f62f" target="_blank">6c6f62f</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6c6f62f');">
    Add index_files directive into the server part configuration
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6c6f62f');">
    // Christopher Faulet
  </div>
  <div id="msg-6c6f62f" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6c6f62f');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Wed Jul 11 15:08:10 2012</strong>

Add index_files directive into the server part configuration

This directive sets the list of resources to look for, when a directory is
requested by the client. If the last entry begins with a "/", and none of
the earlier resources are found, Yaws will perform a redirect to this uri.

Default is:
  index_files = index.yaws index.html index.php
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/5b34d48" target="_blank">5b34d48</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-5b34d48');">
    wrap SSL sockets in tuple
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-5b34d48');">
    // Steve Vinoski
  </div>
  <div id="msg-5b34d48" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-5b34d48');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Apr 21 00:36:04 2012</strong>

wrap SSL sockets in tuple

Yaws previously internally used details of an SSL socket representation
that's supposed to be private/opaque to Erlang's SSL support. Encapsulate
SSL sockets within a {ssl, SslSocket} tuple and add the
yaws_api:get_sslsocket/1 function that returns a socket for SSL sockets or
undefined for non-SSL sockets. Also document the new get_sslsocket/1
function and other minor tweaks to SSL areas of the documentation.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6948590" target="_blank">6948590</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6948590');">
    minor changes to server-sent events
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6948590');">
    // Steve Vinoski
  </div>
  <div id="msg-6948590" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6948590');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jun 29 18:24:59 2012</strong>

minor changes to server-sent events

Change yaws_sse to send close connection header by default, and change the
example to return an Allow header if anything other than GET is requested.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/6561513" target="_blank">6561513</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-6561513');">
    Fix test on the return value of peername/2 in close_accepted_if_max/2
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-6561513');">
    // Christopher Faulet
  </div>
  <div id="msg-6561513" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-6561513');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher.faulet@capflam.org&gt;</strong>
<strong>Date:   Sat Jul 7 19:28:12 2012</strong>

Fix test on the return value of peername/2 in close_accepted_if_max/2
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ba07506" target="_blank">ba07506</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ba07506');">
    Refactor Set-Cookie/Cookie header parsing to follow RFC6265
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ba07506');">
    // Christopher Faulet
  </div>
  <div id="msg-ba07506" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ba07506');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Mon Jul 9 18:41:00 2012</strong>

Refactor Set-Cookie/Cookie header parsing to follow RFC6265

RFC6265 obsoletes RFC2965 and RFC2109. #setcookie{} and #cookie{} are
changed to reflect this new RFC. So, yaws_api:parse_set_cookie/1 and
yaws_api:parse_cookie/1 are refactored accordingly:

* yaws_api:parse_set_cookie/1: Because RFC2109 and RFC2965 are still used,
  we try to be backward compatible with these old RFCs. So this function
  returns a #setcookie{} record when only one cookie is found else it returns
  a list of #setcookie{} records.
  in RFC2109 and RFC2965, cookies are separated by comma. So, comma is
  forbidden in 'path-av' and 'extension-av' except for double-quoted value.
  The parsing are not really strict because of the compatibility and can lead
  to unwanted behaviors.
  Old attributes (like 'Comment' or 'Port') are still parsed and can be
  found into #setcookie.extensions field.

* yaws_api:parse_cookie/1: This function follows the RFC6265, so all cookie
  attributes (like '$Domain' or '$Path') are parsed like any other cookie.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/caa121a" target="_blank">caa121a</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-caa121a');">
    added customization for ibrowse timeout parameter since it is not overridable
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-caa121a');">
    // Kaloyan Dimitrov
  </div>
  <div id="msg-caa121a" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-caa121a');">
    <pre>
<strong>Author: Kaloyan Dimitrov &lt;kaloyan.dimitrov@sumup.com&gt;</strong>
<strong>Date:   Mon Jul 9 15:59:26 2012</strong>

added customization for ibrowse timeout parameter since it is not overridable
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/0c1112d" target="_blank">0c1112d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-0c1112d');">
    added export for the newly introduced call/8
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-0c1112d');">
    // Kaloyan Dimitrov
  </div>
  <div id="msg-0c1112d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-0c1112d');">
    <pre>
<strong>Author: Kaloyan Dimitrov &lt;kaloyan.dimitrov@sumup.com&gt;</strong>
<strong>Date:   Mon Jul 9 15:36:32 2012</strong>

added export for the newly introduced call/8
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/2d33061" target="_blank">2d33061</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-2d33061');">
    -enabled http client library options customization
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-2d33061');">
    // Kaloyan Dimitrov
  </div>
  <div id="msg-2d33061" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-2d33061');">
    <pre>
<strong>Author: Kaloyan Dimitrov &lt;kaloyan.dimitrov@sumup.com&gt;</strong>
<strong>Date:   Mon Jul 9 15:31:35 2012</strong>

-enabled http client library options customization
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a721cfc" target="_blank">a721cfc</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a721cfc');">
    minor changes to server-sent events
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a721cfc');">
    // Steve Vinoski
  </div>
  <div id="msg-a721cfc" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a721cfc');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Sat Jul 7 01:52:21 2012</strong>

minor changes to server-sent events

Change yaws_sse to send close connection header by default, and change the
example to return an Allow header if anything other than GET is requested.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/241ec4d" target="_blank">241ec4d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-241ec4d');">
    Merge pull request #113 from tuncer/reltool-update
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-241ec4d');">
    // Steve Vinoski
  </div>
  <div id="msg-241ec4d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-241ec4d');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jul 6 19:34:40 2012</strong>

Merge pull request #113 from tuncer/reltool-update

Sync with upstream rebar node template
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/39aae44" target="_blank">39aae44</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-39aae44');">
    Sync with upstream rebar node template
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-39aae44');">
    // Tuncer Ayaz
  </div>
  <div id="msg-39aae44" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-39aae44');">
    <pre>
<strong>Author: Tuncer Ayaz &lt;tuncer.ayaz@gmail.com&gt;</strong>
<strong>Date:   Fri Jul 6 18:47:06 2012</strong>

Sync with upstream rebar node template
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/32d4de1" target="_blank">32d4de1</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-32d4de1');">
    -fixed action header for soap12 requests to contain action rather than operation; -added namespace registry to allow for wsdl inline schemas in different namespaces
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-32d4de1');">
    // Kaloyan Dimitrov
  </div>
  <div id="msg-32d4de1" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-32d4de1');">
    <pre>
<strong>Author: Kaloyan Dimitrov &lt;kaloyan.dimitrov@sumup.com&gt;</strong>
<strong>Date:   Fri Jul 6 10:43:08 2012</strong>

-fixed action header for soap12 requests to contain action rather than operation;
-added namespace registry to allow for wsdl inline schemas in different namespaces
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3a8e071" target="_blank">3a8e071</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3a8e071');">
    Fix parse_set_cookie/1 and format_set_cookie/1 functions
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3a8e071');">
    // Christopher Faulet
  </div>
  <div id="msg-3a8e071" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3a8e071');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher.faulet@capflam.org&gt;</strong>
<strong>Date:   Wed Jul 4 19:44:16 2012</strong>

Fix parse_set_cookie/1 and format_set_cookie/1 functions

1. According to the RFCs 2109 and 2965, multiple cookies can be set in a
single 'Set-Cookie' header. So, yaws_api:parse_set_cookie/1 now returns a
list of #setcookie{} records. If no cookie was found or if an error occurred,
it returns []. The parsing is also improved.
Note that this fix breaks the compatibility with previous versions.

2. In yaws_api:format_set_cookie/1, options are now always formated as
quoted-strings.

3. 2 new functions are added, yaws_api:parse_cookie/1 and
yaws_api:format_cookie/1, to parse and format 'Cookie' headers. To let these
functions to work, the #cookie{} record was introduced.

Documentation and testsuite are updated accordingly.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/be0babd" target="_blank">be0babd</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-be0babd');">
    remove duplicate entry from 1.94 news
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-be0babd');">
    // Steve Vinoski
  </div>
  <div id="msg-be0babd" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-be0babd');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jun 29 11:11:32 2012</strong>

remove duplicate entry from 1.94 news
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/da6d73c" target="_blank">da6d73c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-da6d73c');">
    remove unnecessary inet:setopts from server-sent events example
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-da6d73c');">
    // Steve Vinoski
  </div>
  <div id="msg-da6d73c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-da6d73c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jun 29 11:10:04 2012</strong>

remove unnecessary inet:setopts from server-sent events example
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8dd9f23" target="_blank">8dd9f23</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8dd9f23');">
    add doc for new functions for manipulating #headers{} records
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8dd9f23');">
    // Steve Vinoski
  </div>
  <div id="msg-8dd9f23" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8dd9f23');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Jun 27 20:01:51 2012</strong>

add doc for new functions for manipulating #headers{} records

Commit cccc5789 added new functions to yaws_api for manipulating #headers
records: set_header/2, set_header/3, get_header/2, and
delete_header/2. This commit adds the documentation.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/d6e7d36" target="_blank">d6e7d36</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-d6e7d36');">
    add note about the sse appmod to the Server-Sent Events yaws page
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-d6e7d36');">
    // Steve Vinoski
  </div>
  <div id="msg-d6e7d36" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-d6e7d36');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Jun 27 19:56:06 2012</strong>

add note about the sse appmod to the Server-Sent Events yaws page
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3947ca3" target="_blank">3947ca3</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3947ca3');">
    Fix is_revproxy/3 and is_redirect_map/2 in yaws.erl
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3947ca3');">
    // Christopher Faulet
  </div>
  <div id="msg-3947ca3" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3947ca3');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Wed Jun 27 15:38:28 2012</strong>

Fix is_revproxy/3 and is_redirect_map/2 in yaws.erl

In these functions, we try to find the longest matching prefix and not
the first anymore. So we can have several revproxy/redirect_map definitions
for which order does not matter.

For example, if we define these revproxy rules (in any order):
  revproxy = /goo    http://www.worldofgoo.com     (1)
  revproxy = /       http://yaws.hyber.org         (2)
  revproxy = /erl    http://www.erlang.org         (3)
  revproxy = /google http://www.google.com         (4)

then
  http://localhost will match the rule (2)
  http://localhost/goo will match the rule (1)
  http://localhost/google/search will match the rule (4)
  http://localhost/erl will match the rule (3)

We also change how the matching is made. Now, the matching is done by
splitting the path on slashes. So, using previous rules, "/google" is the
longest prefix for the path "/google/test" and "/" is the longest prefix
for "/erlang".
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/be1c395" target="_blank">be1c395</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-be1c395');">
    Fix yaws_api:format_partial_url/2 to avoid strange redirection
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-be1c395');">
    // Christopher Faulet
  </div>
  <div id="msg-be1c395" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-be1c395');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Wed Jun 27 15:31:05 2012</strong>

Fix yaws_api:format_partial_url/2 to avoid strange redirection
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/efc1d1d" target="_blank">efc1d1d</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-efc1d1d');">
    Handle undefined docroot when the fullpath of a request is built
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-efc1d1d');">
    // Christopher Faulet
  </div>
  <div id="msg-efc1d1d" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-efc1d1d');">
    <pre>
<strong>Author: Christopher Faulet &lt;christopher@yakaz.com&gt;</strong>
<strong>Date:   Wed Jun 27 12:28:25 2012</strong>

Handle undefined docroot when the fullpath of a request is built

Now, the internal function yaws_server:construct_fullpath/3 returns
'undefined' when there is no docroot. This might only happen for servers
with an appmod on "/" (because docroot is optional in that case).

Note that such appmods cannot return ssi or yssi structures.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ea1e77b" target="_blank">ea1e77b</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ea1e77b');">
    loosen docroot checking for certain server configs
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ea1e77b');">
    // Steve Vinoski
  </div>
  <div id="msg-ea1e77b" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ea1e77b');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Jun 26 01:59:38 2012</strong>

loosen docroot checking for certain server configs

For server configurations that define a reverse proxy, redirection for the
path "/", forward proxies, or appmods on "/", a docroot isn't
needed. Change yaws_config to avoid errors for missing docroot settings for
such servers. Add test/t6 to check these configurations.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/8862645" target="_blank">8862645</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-8862645');">
    use localtime not universaltime for server_sent_events example
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-8862645');">
    // Steve Vinoski
  </div>
  <div id="msg-8862645" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-8862645');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Wed Jun 27 00:33:09 2012</strong>

use localtime not universaltime for server_sent_events example

Looks like httpd_util:rfc1123_date/1 wants local time, not UTC time, as its
time argument. The server_sent_events example uses that function to create
the server date string events.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/3718543" target="_blank">3718543</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-3718543');">
    Merge pull request #111 from tuncer/typo
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-3718543');">
    // Steve Vinoski
  </div>
  <div id="msg-3718543" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-3718543');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Tue Jun 26 13:22:37 2012</strong>

Merge pull request #111 from tuncer/typo

Fix trivial typo in server_sent_events.yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/fd81730" target="_blank">fd81730</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-fd81730');">
    Fix trivial typo in server_sent_events.yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-fd81730');">
    // Tuncer Ayaz
  </div>
  <div id="msg-fd81730" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-fd81730');">
    <pre>
<strong>Author: Tuncer Ayaz &lt;tuncer.ayaz@gmail.com&gt;</strong>
<strong>Date:   Tue Jun 26 12:24:32 2012</strong>

Fix trivial typo in server_sent_events.yaws
    </pre>
  </div>
</div>
