<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/38bce37" target="_blank">38bce37</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-38bce37');">
    prepare for 1.94
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-38bce37');">
    // Claes Wikstrom
  </div>
  <div id="msg-38bce37" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-38bce37');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jun 25 23:44:17 2012</strong>

prepare for 1.94
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c160d87" target="_blank">c160d87</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c160d87');">
    add news items for upcoming 1.94
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c160d87');">
    // Steve Vinoski
  </div>
  <div id="msg-c160d87" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c160d87');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Jun 25 20:48:41 2012</strong>

add news items for upcoming 1.94
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c4fd143" target="_blank">c4fd143</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c4fd143');">
    add support for W3C Server-Sent Events
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c4fd143');">
    // Steve Vinoski
  </div>
  <div id="msg-c4fd143" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c4fd143');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Fri Jun 1 13:42:59 2012</strong>

add support for W3C Server-Sent Events

Server-Sent Events is a W3C working draft allowing servers to send simple
events to a client. See the documentation in www/server_sent_events.yaws
for a full description.
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/9efbaad" target="_blank">9efbaad</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-9efbaad');">
    Patch from Nico Kruber to fix compile issue on OTP R13
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-9efbaad');">
    // Claes Wikstrom
  </div>
  <div id="msg-9efbaad" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-9efbaad');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Mon Jun 25 11:13:24 2012</strong>

Patch from Nico Kruber to fix compile issue on OTP R13
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/afdddab" target="_blank">afdddab</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-afdddab');">
    prepare for 1.94
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-afdddab');">
    // Claes Wikstrom
  </div>
  <div id="msg-afdddab" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-afdddab');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jun 24 23:51:38 2012</strong>

prepare for 1.94
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/a8d2b52" target="_blank">a8d2b52</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-a8d2b52');">
    Merge branch 'master' of github.com:klacke/yaws
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-a8d2b52');">
    // Claes Wikstrom
  </div>
  <div id="msg-a8d2b52" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-a8d2b52');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jun 24 23:45:23 2012</strong>

Merge branch 'master' of github.com:klacke/yaws
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/ed75b53" target="_blank">ed75b53</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-ed75b53');">
    The random patch for 1.93 wasn't good enough as discovered by Sergei Golovan, we need to cater for non printable chars
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-ed75b53');">
    // Claes Wikstrom
  </div>
  <div id="msg-ed75b53" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-ed75b53');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Sun Jun 24 23:45:04 2012</strong>

The random patch for 1.93 wasn't good enough as discovered by Sergei Golovan, we need to cater for non printable chars
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/f7d145c" target="_blank">f7d145c</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-f7d145c');">
    fix some compiler warnings in the tests
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-f7d145c');">
    // Steve Vinoski
  </div>
  <div id="msg-f7d145c" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-f7d145c');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Thu Jun 21 22:33:37 2012</strong>

fix some compiler warnings in the tests
    </pre>
  </div>
</div>
<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/cccc578" target="_blank">cccc578</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-cccc578');">
    add reverse proxy intercept module capability
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-cccc578');">
    // Steve Vinoski
  </div>
  <div id="msg-cccc578" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-cccc578');">
    <pre>
<strong>Author: Steve Vinoski &lt;vinoski@ieee.org&gt;</strong>
<strong>Date:   Mon Jun 18 02:08:08 2012</strong>

add reverse proxy intercept module capability

Users can now specify an interception module that can rewrite requests and
responses as they pass through the Yaws reverse proxy. See the
documentation for details (yaws.conf.5 man page or the yaws.pdf file).

Also add new set_header, get_header, and delete_header functions to the
yaws_api module to allow intercept modules and arg rewriters to more easily
examine and modify #headers{} records.

Add new tests for the new header manipulation functions and for the reverse
proxy interception feature.
    </pre>
  </div>
</div>
