<div class="git-log">
  <div class="git-commit">
    [<a href="https://github.com/klacke/yaws/commit/c06e4d5" target="_blank">c06e4d5</a>]
  </div>
  <div class="git-title-msg" onclick="toggleVisibility('#msg-c06e4d5');">
    preparing for yaws 1.97
  </div>
  <div class="git-info" onclick="toggleVisibility('#msg-c06e4d5');">
    // Claes Wikstrom
  </div>
  <div id="msg-c06e4d5" class="git-body-msg" style="display: none;" onclick="toggleVisibility('#msg-c06e4d5');">
    <pre>
<strong>Author: Claes Wikstrom &lt;klacke@hyber.org&gt;</strong>
<strong>Date:   Wed Oct 16 06:19:20 2013</strong>

preparing for yaws 1.97
    </pre>
  </div>
</div>
